### ISSUE TITLE
kubernetes failed to correctly resume after azure forced node reboot

### ISSUE THREAD

**Issue by JonathanFraser** [Azure/acs-engine#309] opened 2017-02-20 18:17 UTC
cluster deployed as single master with 5 minions. Azure rebooted the master node (presumably due to scheduled host maintenance), however the cluster failed to correctly resume. Upon logging into master I found that only the kubelet docker container was running and the logs indicated connectivity issues
```
E0220 17:44:12.208801   22127 kubelet.go:1508] Failed creating a mirror pod for "kube-addon-manager-k8s-master-20716856-0_kube-system(4b02c09fb990525f2548d52467175d3a)": Post https://10.240.255.5:443/api/v1/namespaces/kube-system/pods: dial tcp 10.240.255.5:443: getsockopt: connection refused
W0220 17:44:12.208929   22127 status_manager.go:451] Failed to update status for pod "_()": Get https://10.240.255.5:443/api/v1/namespaces/kube-system/pods/kube-addon-manager-k8s-master-20716856-0: dial tcp 10.240.255.5:443: getsockopt: connection refused
E0220 17:44:12.274228   22127 reflector.go:188] pkg/kubelet/config/apiserver.go:44: Failed to list *api.Pod: Get https://10.240.255.5:443/api/v1/pods?fieldSelector=spec.nodeName%3Dk8s-master-20716856-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
E0220 17:44:12.274431   22127 reflector.go:188] pkg/kubelet/kubelet.go:386: Failed to list *api.Node: Get https://10.240.255.5:443/api/v1/nodes?fieldSelector=metadata.name%3Dk8s-master-20716856-0&resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
E0220 17:44:12.281397   22127 reflector.go:188] pkg/kubelet/kubelet.go:378: Failed to list *api.Service: Get https://10.240.255.5:443/api/v1/services?resourceVersion=0: dial tcp 10.240.255.5:443: getsockopt: connection refused
```
which would of course occur is the kubelet hadn't started them yet. a `service kubelet restart` correctly restarted the master  with all the master services correctly resuming. However, there still appears to be issues. a `kubectl get nodes` shows all the minions, however, they are in a not ready state. The stated reason for the node issues is `Kubelet failed to get node info`

**Comment by siamak-haschemi** [comment] 2017-02-20 19:25
We experienced something similar. When restarting minions one-by-one, everything works as expected and the nodes come back to a ready state.

However, when the master is restarted, the minions are not able to reconnected to the master for a long time (>5 min, is this long?). 

But after a while, they came back to normal state. So @JonathanFraser, maybe it just takes more time then you expected?

**Comment by JonathanFraser** [comment] 2017-02-20 19:42
The master was rebooted over the weekend and it failed to correctly resume by monday morning so thats not it. Even after issuing the `service kublet restart` the minions have persisted in a NotReady state for over 2 hours now.

**Comment by colemickens** [comment] 2017-02-20 20:32
When was this cluster booted? And using what revision of `acs-engine`?

**Comment by colemickens** [comment] 2017-02-20 20:33
I also need the `kube-controller-manager` logs from the master (or via `kubectl`) and a log from one of the `kubelet`s that is marked NotReady.

**Comment by siamak-haschemi** [comment] 2017-02-20 20:58
> I also need the kube-controller-manager logs from the master (or via kubectl) and a log from one of the kubelets that is marked NotReady.

Just a 10.000 feed observation: @colemickens You ask in different ticket for those log files. Wouldn't it be possible to automate the collection of those files in a zip-file (somehow)? 

Or at least a page which shows the steps to collect those files (we have some newbies here)? I would be happy to help.

Sorry for hijacking @JonathanFraser

**Comment by colemickens** [comment] 2017-02-20 21:00
@siamak-haschemi Good idea, but please feel free to file a separate issue. At the very least I can make something that can be easily copy/pasted.

**Comment by siamak-haschemi** [comment] 2017-02-20 21:09
@colemickens Done: #310

**Comment by JonathanFraser** [comment] 2017-02-20 22:12
Cluster was booted about a month ago with acs-engine version: `7cd3e7f7d17c59e6fe4b014e61688bba3df92cfa`
the pin to docker 1.12.6

logs available [here](https://drive.google.com/open?id=0BxlruhDKyCC6SXhFaDlEWXpubFk)

**Comment by colemickens** [comment] 2017-02-21 19:45
@raveeram Is the ILB used even for a single master? that would explain what @siamak-haschemi is reporting.

As for not coming back for hours/days... that's certainly unexpected. It's very strange the kubelet would be healthy on the master but not running the components. I've never seen that before. Usually kubelet cycles if the SP is bad, or comes up and brings up the master components.

@JonathanFraser if you look at `docker ps -a` on the master, is it even trying to start up the master components?

**Comment by colemickens** [comment] 2017-02-21 19:47
@JonathanFraser unfortunately, I also need `kubelet` from the master so I can try to guess why it's not launching the master components. Sorry, but can you supply it as well? Thanks.

**Comment by JonathanFraser** [comment] 2017-02-21 20:09
Had you sent that an hour ago I could have got that for you, we have already torn the cluster down.

**Comment by colemickens** [comment] 2017-02-21 20:13
I'm sorry about that @JonathanFraser. Unfortunately, without it, I can't triage what happened here. I'll take a crack at #310 this week so that we can automate this process for a better RCA in the future.

@siamak-haschemi Can you please file a separate issue for the problem you experienced? I think that's a known issue due to our new HA configuration and an upstream bug in kubernetes.

Closing as this is not going to be actionable.

**Closed by colemickens** 2017-02-21 20:13 UTC

**Comment by siamak-haschemi** [comment] 2017-02-21 20:40
To not waste your time, and to have reproducible steps, I would need to create a cluster to verify this behavior. When I hit it the next time, I create the ticket.

**Comment by naveena-s** [comment] 2017-06-01 14:36
Was this resolved?? I am facing the same issue

**Comment by JackQuincy** [comment] 2017-06-01 17:51
@anhowe made a change in how we provision vms. It takes a new cluster to take the fix.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by RossWilliams** [comment] 2017-06-01 20:03
@JackQuincy Do you have a PR # for the change? I'd like to explore manually making this change before rebuilding a cluster.

**Comment by JackQuincy** [comment] 2017-06-01 20:41
#661 is the build. If your cluster is new enough to have the attached disks, which it looks like it is if you are hitting these issues. The easiest thing to should be to try our new upgrade operation. @amanohar details the process in issue #464 it is new though and might take a bit of doing to get right. So your choice on ig you want to try to manually update or use the script. Our process is set up in PR #707.
