### ISSUE TITLE
getsockopt: connection refused since v0.18.5

### ISSUE THREAD

**Issue by msornay** [Azure/acs-engine#3283] opened 2018-06-15 08:55 UTC
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.18.5

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.10

**What happened**:

On cluster created with acs-engine v0.18.5, network liveliness probes are flaky and often fail with an error message like : ` dial tcp 10.240.0.38:80: getsockopt: connection refused`

This can happen for every pods we use. Clusters deployed with version v0.18.3 work fine (#3153 aside)

**How to reproduce it** (as minimally and precisely as possible):

Here is the definition : 

```{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "XXX",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "cpuworkers",
        "count": 2,
        "vmSize": "Standard_D16s_v3",
        "availabilityProfile": "VirtualMachineScaleSets"
      }
    ],
    "linuxProfile": {
      "adminUsername": "cluster",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

The following install with helm (as an example) will lead to failing pods : 
`helm install --name ddagent --set datadog.apiKey=<api_key> stable/datadog`

**Comment by jackfrancis** [comment] 2018-06-15 18:07
@sharmasushant @tamilmani1989 Do we have any test data that suggests this change introduced add'l network flakiness?

https://github.com/Azure/acs-engine/commit/77b9e9346c256e6de76a9ed853926b8b2da00460

(That change went in between v0.18.3 and v0.18.5)

**Comment by SteveCurran** [comment] 2018-06-15 18:31
Seeing same issue on 18.5 deployment this morning. Started with Tiller, now getting it on DNS.

**Comment by jackfrancis** [comment] 2018-06-15 19:12
@SteveCurran would you be willing to try the previous version of Azure CNI to see if that addresses your situation?

```
curl -fsSL https://acs-mirror.azureedge.net/cni/azure-vnet-cni-linux-amd64-v1.0.4.tgz -o /tmp/azure_cni_1.0.4.tgz
sudo tar -xvzf /tmp/azure_cni_1.0.4.tgz azure-vnet -C /opt/cni/bin/
sudo tar -xvzf /tmp/azure_cni_1.0.4.tgz azure-vnet-ipam -C /opt/cni/bin/
sudo tar -xvzf /tmp/azure_cni_1.0.4.tgz 10-azure.conflist -C /etc/cni/net.d/
```

On every node (master + agents). And to be extra sure a vm reboot.

That's a lot of extra credit work, but it might give us data that suggests we have a regression in v1.0.6. Thanks!

**Comment by msornay** [comment] 2018-06-15 19:23
@jackfrancis If that can help, the problem is gone after re-creating the exact same cluster with v0.18.3

**Comment by sharmasushant** [comment] 2018-06-15 21:31
@jackfrancis  Connection refused indicates that server is refusing the connection. CNI cannot cause server side to refuse connections. I suspect there is something else that is causing this. Also, I think @msornay did not just revert CNI, the older acs-engine version was used, which means every change in acs-engine is reverted (and not just cni). 

I suspect if we revert without investigation, we may ship the change that is actually causing it.

**Comment by jackfrancis** [comment] 2018-06-15 21:37
@sharmasushant Here is the commit history of v0.18.5:

https://github.com/Azure/acs-engine/commits/patch-release-v0.18.5

And from v0.18.3:

https://github.com/Azure/acs-engine/commits/patch-release-v0.18.3

There are 6 commits there, and due to (1) the likelihood that changing the Azure CNI implementation is the cause (there are no other comparable changes to underlying network) and (2) the time sensitivity w/ respect to accommodating AKS's release schedule, we will revert as an expression of caution.

We may be wrong! In which case, with some more data, we will rev back to v1.0.6.

In the meantime, if you could look at your own real-world test data of v1.0.6 running on a Kubernetes cluster and report back if you see any comparable flakiness that would be great.

Thanks!

**Comment by sharmasushant** [comment] 2018-06-15 21:38
@msornay Do we know who is expected to be listening on port 80 and if the listener is actually up?

**Comment by sharmasushant** [comment] 2018-06-15 21:43
@sure, you can try to see if reverting cni helps. We can run tests on our side as well. Can you also share starting from what date, you started seeing flakiness in your tests?

**Comment by jackfrancis** [comment] 2018-06-15 21:46
We saw flakiness right after merging. Unfortunately, to confuse things, circleci had an outage on the day this was merged, and was a little flaky itself coming out of that, so I suspect our signalling was a little confused for a while. But as the days progressed the flakiness started to become a pattern. And this customer report nudged us in the direction that a general pattern may be present post-Azure CNI v0.1.6 merge.

**Closed** 2018-06-15 21:47 UTC
Labels: in progress, network

**Comment by sharmasushant** [comment] 2018-06-15 21:48
@jackfrancis I also see that rpcbind and rpc-statd was started at the same time. May be something else you can take a look at.

**Comment by jackfrancis** [comment] 2018-06-15 21:55
We discussed that possibility as well, but in fact missing rpcbind and rpc-statd were a regression that the change you observed fixes. See this in v0.16.0:

https://github.com/Azure/acs-engine/blob/v0.16.0/parts/k8s/kubernetesagentcustomdata.yml#L187

We did not observe any such network flakiness in that or prior versions so we do not suspect the re-introduction of rpcbind and rpc-statd to be the cause.

**Comment by sylr** [comment] 2018-07-06 12:58
I'm wondering if this could be the source of DNS resolution problems I'm having on a cluster running 1.10.4 and Azure CNI 1.0.6 :

```
root@ubuntu-79c745bbd8-kc566:/# curl -s http://abstraction.fr/ > /dev/null
09:31:37.554648 IP (tos 0x0, ttl 64, id 11882, offset 0, flags [DF], proto UDP (17), length 86)
    ubuntu-79c745bbd8-kc566.49203 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c4e -> 0xfb4b!] 1272+ A? abstraction.fr.default.svc.cluster.local. (58)
09:31:37.554790 IP (tos 0x0, ttl 64, id 11883, offset 0, flags [DF], proto UDP (17), length 86)
    ubuntu-79c745bbd8-kc566.49203 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c4e -> 0xe529!] 6911+ AAAA? abstraction.fr.default.svc.cluster.local. (58)
09:31:37.556385 IP (tos 0x0, ttl 62, id 24898, offset 0, flags [DF], proto UDP (17), length 179)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.49203: [udp sum ok] 6911 NXDomain q: AAAA? abstraction.fr.default.svc.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (151)
    
09:31:42.559682 IP (tos 0x0, ttl 64, id 12320, offset 0, flags [DF], proto UDP (17), length 86)
    ubuntu-79c745bbd8-kc566.49203 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c4e -> 0xfb4b!] 1272+ A? abstraction.fr.default.svc.cluster.local. (58)
09:31:42.560617 IP (tos 0x0, ttl 62, id 25733, offset 0, flags [DF], proto UDP (17), length 179)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.49203: [udp sum ok] 1272 NXDomain q: A? abstraction.fr.default.svc.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (151)
09:31:42.560713 IP (tos 0x0, ttl 64, id 12321, offset 0, flags [DF], proto UDP (17), length 86)
    ubuntu-79c745bbd8-kc566.49203 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c4e -> 0xe529!] 6911+ AAAA? abstraction.fr.default.svc.cluster.local. (58)
09:31:42.561389 IP (tos 0x0, ttl 62, id 25734, offset 0, flags [DF], proto UDP (17), length 179)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.49203: [udp sum ok] 6911 NXDomain q: AAAA? abstraction.fr.default.svc.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (151)
09:31:42.561540 IP (tos 0x0, ttl 64, id 12322, offset 0, flags [DF], proto UDP (17), length 78)
    ubuntu-79c745bbd8-kc566.58962 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c46 -> 0x4733!] 18236+ A? abstraction.fr.svc.cluster.local. (50)
09:31:42.562690 IP (tos 0x0, ttl 62, id 25735, offset 0, flags [DF], proto UDP (17), length 171)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.58962: [udp sum ok] 18236 NXDomain q: A? abstraction.fr.svc.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (143)
09:31:42.562743 IP (tos 0x0, ttl 64, id 12323, offset 0, flags [DF], proto UDP (17), length 78)
    ubuntu-79c745bbd8-kc566.58962 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c46 -> 0x6dcd!] 8327+ AAAA? abstraction.fr.svc.cluster.local. (50)
09:31:42.563457 IP (tos 0x0, ttl 62, id 25736, offset 0, flags [DF], proto UDP (17), length 171)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.58962: [udp sum ok] 8327 NXDomain q: AAAA? abstraction.fr.svc.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (143)
09:31:42.563531 IP (tos 0x0, ttl 64, id 12324, offset 0, flags [DF], proto UDP (17), length 74)
    ubuntu-79c745bbd8-kc566.37056 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c42 -> 0xaca3!] 3552+ A? abstraction.fr.cluster.local. (46)
09:31:42.564678 IP (tos 0x0, ttl 62, id 25737, offset 0, flags [DF], proto UDP (17), length 167)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.37056: [udp sum ok] 3552 NXDomain q: A? abstraction.fr.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (139)
09:31:42.564754 IP (tos 0x0, ttl 64, id 12325, offset 0, flags [DF], proto UDP (17), length 74)
    ubuntu-79c745bbd8-kc566.37056 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c42 -> 0x7028!] 19008+ AAAA? abstraction.fr.cluster.local. (46)
09:31:42.565555 IP (tos 0x0, ttl 62, id 25738, offset 0, flags [DF], proto UDP (17), length 167)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.37056: [udp sum ok] 19008 NXDomain q: AAAA? abstraction.fr.cluster.local. 0/1/0 ns: cluster.local. SOA ns.dns.cluster.local. hostmaster.cluster.local. 1530867600 28800 7200 604800 60 (139)
09:31:42.565689 IP (tos 0x0, ttl 64, id 12326, offset 0, flags [DF], proto UDP (17), length 112)
    ubuntu-79c745bbd8-kc566.43607 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c68 -> 0x05dd!] 55424+ A? abstraction.fr.frh2mpjefqcedg0y3yjpi5zilh.ax.internal.cloudapp.net. (84)
09:31:42.567987 IP (tos 0x0, ttl 62, id 25739, offset 0, flags [DF], proto UDP (17), length 167)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.43607: [udp sum ok] 55424 NXDomain* q: A? abstraction.fr.frh2mpjefqcedg0y3yjpi5zilh.ax.internal.cloudapp.net. 0/1/0 ns: ax.internal.cloudapp.net. SOA localhost. hostmaster. 272071 900 600 86400 10 (139)
09:31:42.568050 IP (tos 0x0, ttl 64, id 12327, offset 0, flags [DF], proto UDP (17), length 112)
    ubuntu-79c745bbd8-kc566.43607 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c68 -> 0x5778!] 34506+ AAAA? abstraction.fr.frh2mpjefqcedg0y3yjpi5zilh.ax.internal.cloudapp.net. (84)
09:31:42.569908 IP (tos 0x0, ttl 62, id 25740, offset 0, flags [DF], proto UDP (17), length 167)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.43607: [udp sum ok] 34506 NXDomain* q: AAAA? abstraction.fr.frh2mpjefqcedg0y3yjpi5zilh.ax.internal.cloudapp.net. 0/1/0 ns: ax.internal.cloudapp.net. SOA localhost. hostmaster. 272071 900 600 86400 10 (139)
09:31:42.569994 IP (tos 0x0, ttl 64, id 12328, offset 0, flags [DF], proto UDP (17), length 60)
    ubuntu-79c745bbd8-kc566.51591 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c34 -> 0x796b!] 912+ A? abstraction.fr. (32)
09:31:42.571364 IP (tos 0x0, ttl 62, id 25741, offset 0, flags [DF], proto UDP (17), length 76)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.51591: [udp sum ok] 912 q: A? abstraction.fr. 1/0/0 abstraction.fr. A 163.172.128.19 (48)
09:31:42.571449 IP (tos 0x0, ttl 64, id 12329, offset 0, flags [DF], proto UDP (17), length 60)
    ubuntu-79c745bbd8-kc566.51591 > kube-dns.kube-system.svc.cluster.local.53: [bad udp cksum 0x1c34 -> 0x4885!] 13403+ AAAA? abstraction.fr. (32)
09:31:42.571979 IP (tos 0x0, ttl 62, id 25742, offset 0, flags [DF], proto UDP (17), length 88)
    kube-dns.kube-system.svc.cluster.local.53 > ubuntu-79c745bbd8-kc566.51591: [udp sum ok] 13403 q: AAAA? abstraction.fr. 1/0/0 abstraction.fr. AAAA 2001:bc8:4400:2000::280f (60)
```

As show in this tcpdump trace I've a 5 seconds delay as it seems that first DNS query never gets a response. This occurs around once every 5 or 6 calls.

**Comment by jackfrancis** [comment] 2018-07-06 15:57
@sylr We are currently testing v1.0.7 of Azure CNI:

https://github.com/Azure/acs-engine/pull/3433

If possible, it'd be great to see if you can repro the above DNS flakiness on a cluster using that version (check out the above branch, build, deploy a cluster).

Are you able to repro the above symptoms quickly/reliably using a new 1.0.6-backed cluster?

**Comment by sylr** [comment] 2018-07-25 08:59
@jackfrancis I've regenerated my cluster with a branch that contains the revert to CNI 1.0.4 and I'm still experiencing the DNS issue.

The only difference I now have between two clusters generated from the same acs-engine commit is `acceleratedNetwork` enabled on the affected cluster.

I'm going to regenerate it again with `acceleratedNetwork` disabled to see if this is the culprit for my issue.

**Comment by jackfrancis** [comment] 2018-07-25 15:49
Thanks for following up. The current release (v0.20.1), which includes Azure CNI v1.0.7 by default, and accelerated networking enabled by default (for VM SKUs that support accelerated networking) is the current best-known option. Please feel free to experiment w/ accelerated networking disabled, we haven't observed any operational issues as a result of that option.
