### ISSUE TITLE
Unable to update the configuration of an existent cluster 

### ISSUE THREAD

**Issue by EcaterinaGr** [Azure/acs-engine#4260] opened 2018-11-16 15:23 UTC
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Yes
---

**What version of acs-engine?**:
0.21.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10.7

**What happened**:
The goal was to enable AAD authentication feature on an existent cluster. Was unable to update the cluster, without destroying it. 

**What you expected to happen**:
There should be a command to update the existent cluster (parameters from acs engine template file) without destroying it (not only adding AAD authentication, but also changing the add-ons, adding agentPoolProfile, changing availabilityProfile, changing vmSize, etc)

**How to reproduce it** (as minimally and precisely as possible):
1) Change the acs engine template - add aadProfile
2) Generate the arm templates - acs engine generate
3) Create the cluster from arm templates - az group deployment create. 

**Anything else we need to know**:
Tried to use "acs-engine upgrade" command instead of "az group deployment create" but that does not work neither.

**Comment by CecileRobertMichon** [comment] 2018-11-21 22:10
duplicate of https://github.com/Azure/acs-engine/issues/4170

**Comment by CecileRobertMichon** [comment] 2018-11-21 22:10
@EcaterinaGr this is something we have on our backlog and would like to implement in the near future, stay tuned!

**Comment by CecileRobertMichon** [comment] 2018-12-07 19:09
Closing in favor of #4170

**Closed** 2018-12-07 19:15 UTC
