### ISSUE TITLE
Metric Server CrashLoopBackOff on newly deployed clusters

### ISSUE THREAD

**Issue by esheris** [Azure/acs-engine#2665] opened 2018-04-12 17:02 UTC
**Is this a request for help?**:

Help would be nice but really I don't see any other posts about this. My config is super basic. 

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

15.1

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Newly deployed cluster, 1.10.0 (and previous version 1.9.6) metrics-server comes up and just sits in CrashLoopBackOff

**What you expected to happen**:
metric server doesnt go into crashloopbackoff

**How to reproduce it** (as minimally and precisely as possible):
deploy a new cluster using acs-engine 15.1

**Anything else we need to know**:
Cluster Config:
```
{
    "apiVersion": "vlabs",
    "name": "liveball-dev-test",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.10",
        "kubernetesConfig": {
        }
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "liveball-dev-test",
        "vmSize": "Standard_A2"
      },
      "agentPoolProfiles": [
        {
          "name": "linuxpool",
          "count": 2,
          "vmSize": "Standard_A2_v2",
          "availabilityProfile": "AvailabilitySet"
        },
        {
          "name": "winpool",
          "count": 2,
          "vmSize": "Standard_A2_v2",
          "storageProfile": "ManagedDisks",
          "availabilityProfile": "AvailabilitySet",
          "osDiskSizeGB": 200,
          "osType": "Windows"
        }
      ],
      "windowsProfile": {
        "adminUsername": "azureuser",
        "adminPassword": "<replaced>"
      },
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": "<replaced>
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "<replaced>",
        "secret": "<replaced>"
      }
    }
  }
```
Kubectl logs for metric server:
```
PS C:\Users\Eric\kubernetes\ClusterCreation-Config\helmfile> kubectl logs -n kube-system metrics-server-7fcdc5dbb9-qgh6q
I0412 16:49:58.181992       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0412 16:49:58.182145       1 heapster.go:72] Metrics Server version v0.2.1
I0412 16:49:58.182781       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version
I0412 16:49:58.182873       1 configs.go:62] Using kubelet port 10255
I0412 16:49:58.186311       1 heapster.go:128] Starting with Metric Sink
I0412 16:49:58.536710       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0412 16:49:59.614300       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file
```
kubectl describe 
```
Name:           metrics-server-7fcdc5dbb9-qgh6q
Namespace:      kube-system
Node:           k8s-linuxpool-11499228-1/10.240.0.66
Start Time:     Thu, 12 Apr 2018 09:07:41 -0700
Labels:         k8s-app=metrics-server
                pod-template-hash=3978718665
Annotations:    <none>
Status:         Running
IP:             10.240.0.67
Controlled By:  ReplicaSet/metrics-server-7fcdc5dbb9
Containers:
  metrics-server:
    Container ID:  docker://6b82f6aae3b848555876c5b701210954039883795438c230b8ddd9f4ec748101
    Image:         k8s-gcrio.azureedge.net/metrics-server-amd64:v0.2.1
    Image ID:      docker-pullable://k8s-gcrio.azureedge.net/metrics-server-amd64@sha256:49a9f12f7067d11f42c803dbe61ed2c129995
9ad85cb315b25ff7eef8e6b8892
    Port:          <none>
    Command:
      /metrics-server
      --source=kubernetes.summary_api:''
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 12 Apr 2018 09:49:58 -0700
      Finished:     Thu, 12 Apr 2018 09:49:59 -0700
    Ready:          False
    Restart Count:  13
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-6zp7g (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  metrics-server-token-6zp7g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-6zp7g
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                 Age                 From                               Message
  ----     ------                 ----                ----                               -------
  Normal   Scheduled              46m                 default-scheduler                  Successfully assigned metrics-server-7fcdc5dbb9-qgh6q to k8s-linuxpool-11499228-1
  Normal   SuccessfulMountVolume  46m                 kubelet, k8s-linuxpool-11499228-1  MountVolume.SetUp succeeded for volume "metrics-server-token-6zp7g"
  Normal   Pulled                 45m (x4 over 46m)   kubelet, k8s-linuxpool-11499228-1  Successfully pulled image "k8s-gcrio.azureedge.net/metrics-server-amd64:v0.2.1"
  Normal   Created                45m (x4 over 46m)   kubelet, k8s-linuxpool-11499228-1  Created container
  Normal   Started                45m (x4 over 46m)   kubelet, k8s-linuxpool-11499228-1  Started container
  Normal   Pulling                44m (x5 over 46m)   kubelet, k8s-linuxpool-11499228-1  pulling image "k8s-gcrio.azureedge.net/metrics-server-amd64:v0.2.1"
  Warning  BackOff                1m (x201 over 45m)  kubelet, k8s-linuxpool-11499228-1  Back-off restarting failed container
```

**Comment by jsturtevant** [comment] 2018-04-19 17:57
Confirmed with 15.2:

```
acs-engine.exe version
Version: v0.15.2
GitCommit: 2e2fd9a7
GitTreeState: clean

k logs metrics-server-5c74cf6d4f-dv298 -n kube-system
I0419 17:50:30.804229       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0419 17:50:30.804353       1 heapster.go:72] Metrics Server version v0.2.1
I0419 17:50:30.804560       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version
I0419 17:50:30.804607       1 configs.go:62] Using kubelet port 10255
I0419 17:50:30.805966       1 heapster.go:128] Starting with Metric Sink
I0419 17:50:31.500292       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0419 17:50:31.695991       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file
```

**Comment by jsturtevant** [comment] 2018-04-19 18:06
dupe of #2421

**Comment by adelina-t** [comment] 2018-05-02 14:56
I can confirm I see this issue with acs-engine v0.16.1 and k8s 1.10.2 and k8s 1.9.7 . Also happens with v0.16.0 and k8s 1.9.7.

**Comment by PatrickLang** [comment] 2018-05-02 15:34
@jackfrancis @JiangtianLi - have you been able to check this out?

**Comment by JiangtianLi** [comment] 2018-05-02 16:28
@jsturtevant @adelina-t  Is kube-system metrics-server running on windows node or linux node? From https://github.com/Azure/acs-engine/pull/2727 it is supposed to run only on linux node. Is the cluster windows only and master is not schedulable?

**Comment by adelina-t** [comment] 2018-05-03 06:48
@JiangtianLi 

Running on linux node.

Api model used to deploy cluster:

`{
  "apiVersion": "vlabs",
  "location": "eastus",
  "tags": null,
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "random-prefix",
      "vmSize": "Standard_D2s_v3"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2s_v3",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "key"
          }
        ]
      }
    },
    "windowsProfile": {
          "adminUsername": "",
          "adminPassword": ""
    },
    "servicePrincipalProfile": {
      "clientId": 
      "secret": 
    }
  }
}
 `

**Comment by adelina-t** [comment] 2018-05-03 07:00
K8s 1.10.2 with ACS v.0.6.1 and K8s 1.9.7 with ACS v.0.6.1 have the same exact issue. If you need other logs or info, I can provide them.

**Comment by jsturtevant** [comment] 2018-05-03 20:45
@JiangtianLi I had already updated the pod to schedule it on a linux node, the output from the pod confirms that it is on a linux node and failing:

```
 k describe po metrics-server-5c74cf6d4f-dv298 -n kube-system
Name:           metrics-server-5c74cf6d4f-dv298
Namespace:      kube-system
Node:           k8s-linuxpool2-42478050-0/10.240.0.65
Start Time:     Thu, 19 Apr 2018 10:47:15 -0700
Labels:         k8s-app=metrics-server
                pod-template-hash=1730792809
Annotations:    <none>
Status:         Running
IP:             10.240.0.76
Controlled By:  ReplicaSet/metrics-server-5c74cf6d4f
Containers:
  metrics-server:
    Container ID:  docker://a04732abc1c43e4ad7701b81586b0459c90a9e58fa063a7fa4ca579d2f68d473
    Image:         k8s-gcrio.azureedge.net/metrics-server-amd64:v0.2.1
    Image ID:      docker-pullable://k8s-gcrio.azureedge.net/metrics-server-amd64@sha256:49a9f12f7067d11f42c803dbe61ed2c1299959ad85cb315b25ff7eef8e6b8892
    Port:          <none>
    Command:
      /metrics-server
      --source=kubernetes.summary_api:''
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 03 May 2018 13:38:04 -0700
      Finished:     Thu, 03 May 2018 13:38:05 -0700
    Ready:          False
    Restart Count:  3957
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from metrics-server-token-vmtsq (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  metrics-server-token-vmtsq:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  metrics-server-token-vmtsq
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     <none>
Events:
  Type     Reason   Age                   From                                Message
  ----     ------   ----                  ----                                -------
  Normal   Pulling  23m (x3954 over 14d)  kubelet, k8s-linuxpool2-42478050-0  pulling image "k8s-gcrio.azureedge.net/metrics-server-amd64:v0.2.1"
  Warning  BackOff  3m (x90957 over 14d)  kubelet, k8s-linuxpool2-42478050-0  Back-off restarting failed container
```

and logs from the pod:
```
 k logs  metrics-server-5c74cf6d4f-dv298 -n kube-system
I0503 20:43:15.659344       1 heapster.go:71] /metrics-server --source=kubernetes.summary_api:''
I0503 20:43:15.659461       1 heapster.go:72] Metrics Server version v0.2.1
I0503 20:43:15.659640       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version
I0503 20:43:15.659679       1 configs.go:62] Using kubelet port 10255
I0503 20:43:15.660895       1 heapster.go:128] Starting with Metric Sink
I0503 20:43:15.945858       1 serving.go:308] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
F0503 20:43:16.073282       1 heapster.go:97] Could not create the API server: cluster doesn't provide requestheader-client-ca-file
```

**Comment by karataliu** [comment] 2018-05-04 04:39
It will only fail when agent has windows node. 
Root cause is:
Config for 'requestheader-client-ca-file' is applied to staticLinuxAPIServerConfig, which happens on Line#61
https://github.com/Azure/acs-engine/blob/v0.16.2/pkg/acsengine/defaults-apiserver.go#L61

Copy config is at Line#41
https://github.com/Azure/acs-engine/blob/v0.16.2/pkg/acsengine/defaults-apiserver.go#L41

In this case,  the required properties are not set for windows nodes.

Proposed #2857 as a fix candidate.

**Closed** 2018-05-04 22:14 UTC
