### ISSUE TITLE
Hard to tell which agent pool is a Windows node in

### ISSUE THREAD

**Issue by wenwu449** [Azure/acs-engine#638] opened 2017-05-16 18:57 UTC
for Linux nodes, the nodes have name with "agentpool*" in it. For Windows nodes, this pattern does not work. Would be good if the naming convention is aligned.

**Comment by anhowe** [comment] 2017-05-16 19:19
Thanks @wenwu449.  This is by design, since windows vms only allow 15 characters for node names.  

Alternatively, please use the node selector:

nodeSelector:
  beta.kubernetes.io/os: linux

**Comment by anhowe** [comment] 2017-05-16 20:18
discussed with @wenwu449, closing since this is windows limitation and he has the regex required to match the windows names.

**Closed by anhowe** 2017-05-16 20:18 UTC
