### ISSUE TITLE
ACS VMSize Error

### ISSUE THREAD

**Issue by idealhack** [Azure/acs-engine#438] opened 2017-03-28 05:23 UTC
Hi,

I'm using DC/OS with Azure. I modified [`dcos1.8.8.json`](https://github.com/Azure/acs-engine/blob/master/examples/dcos-versions/dcos1.8.8.json) as below:

```
"agentPoolProfiles": [
  {
    "name": "agentpublic",
    "count": 1,
    "vmSize": "Basic_A2",
    "dnsPrefix": "public",
    "ports": [
      80,
      443,
      8080
    ]
  }
],
```

Deployment failed with this error:

```
error:   The value of parameter sku.tier is invalid.
```

Change `vmSize` to `Standard_A2` then the deployment succeed.

---

The value of `sku.tier` in the template is `Standard`: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/testdata/simple/dcos1.8.8_expected.json#L1320

But `agentpublicVMSize` allows basic VMs: https://github.com/Azure/acs-engine/blob/master/pkg/acsengine/testdata/simple/dcos1.8.8_expected.json#L335

As told by an Azure support engineer, The basic VMs can't be used on ACS. So maybe the test data is wrong?

**Comment by colemickens** [comment] 2017-03-28 08:37
This is a dupe of https://github.com/Azure/acs-engine/issues/352

**Comment by idealhack** [comment] 2017-03-29 02:47
I thought this is not a dupe.

Why would these vmsizes exists in test data since they are not allowed to use?

**Comment by anhowe** [comment] 2017-03-29 03:05
@idealhack Are you using a template created by ACS-Engine or using portal or CLI to create a cluster using the ACS service?

**Comment by idealhack** [comment] 2017-03-29 03:08
I'm using acs-engine like this:

```
vim examples/dcos-versions/dcos1.8.8.json
./acs-engine examples/dcos-versions/dcos1.8.8.json
azure group create -n dcos -l chinaeast
azure group deployment create dcos -f _output/DCOS188-32758952/azuredeploy.json -e _output/DCOS188-32758952/azuredeploy.parameters.json
```

**Comment by anhowe** [comment] 2017-03-29 03:08
Just repro'd, it appears VMSS does not support Basic SKU.  I'm reaching out to VMSS team.  Note that you can use basic on AvailabilitySet.

**Comment by anhowe** [comment] 2017-03-29 03:20
found the root cause:

"Load balancing is not supported for Basic VM sizes."

**Comment by anhowe** [comment] 2017-03-29 03:35
As a workaround you can remove the "ports" to make it a private pool, no loadbalancer will be added, and will actually:

"agentPoolProfiles": [
  {
    "name": "agentpublic",
    "count": 1,
    "vmSize": "Basic_A2"
  }

**Comment by idealhack** [comment] 2017-03-29 03:54
@anhowe Thanks, but this private pool config seems does not work.

**Comment by anhowe** [comment] 2017-03-29 04:28
Looks like you will need to use an availabilityset.  I've just sent an email to VMSS team. 

I've just verified this, so please try the following:

"agentPoolProfiles": [
      {
        "name": "agentprivate",
        "count": 1,
        "vmSize": "Basic_A2",
        "availabilityProfile": "AvailabilitySet"
      }
    ]

**Comment by JackQuincy** [comment] 2017-05-01 22:54
#518 fixes this

**Closed by JackQuincy** 2017-05-01 22:54 UTC
Labels: kind/bug, priority/P1
