### ISSUE TITLE
Windows Kubernetes with custom vnet not deploying - wrong variable name

### ISSUE THREAD

**Issue by NillsF** [Azure/acs-engine#2565] opened 2018-03-30 09:18 UTC
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.14.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
When deploying a Windows Kubernetes cluster with custom VNET, the generated template fails to create the worker VMs. This is due to a wrong variable in the section "customData" of the "osProfile" of the worker VM deployment. The wrong variable is named: variables('subnet'); but the variable 'subnet' is not defined. It is fixable by renaming this variable 'vnetSubnetID'. 
<img width="654" alt="image" src="https://user-images.githubusercontent.com/6205923/38130063-d111c9d4-3401-11e8-8f59-b5f74dfc13f3.png">

**What you expected to happen**:
Deployment to Azure to work without issues.

**How to reproduce it** (as minimally and precisely as possible):
Reproduce error
I am using the following ACS-engine template file:
```json
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes"
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "nfacseissue",
        "vmSize": "Standard_D2s_v3",
        "vnetSubnetId": "/subscriptions/**xxx**/resourceGroups/acs-engine-issue/providers/Microsoft.Network/virtualNetworks/k8s-issue/subnets/Master",
        "firstConsecutiveStaticIP": "10.1.255.1",
        "vnetCidr": "10.0.0.0/8"
      },
      "agentPoolProfiles": [
        {
          "name": "windowspool",
          "count": 2,
          "vmSize": "Standard_D2s_v3",
          "availabilityProfile": "AvailabilitySet",
          "osType": "Windows",
          "vnetSubnetId": "/subscriptions/**xxx**/resourceGroups/acs-engine-issue/providers/Microsoft.Network/virtualNetworks/k8s-issue/subnets/Workers"        }
      ],
      "windowsProfile": {
        "adminUsername": "**xxx**",
        "adminPassword": "**xxx**"
      },
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
                "keyData": "ssh-rsa **xxx**"
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "clientId": "**xxx**",
        "secret": "**xxx**"
      }
    }
  }
```
This generates the wrong template, highlighting the part where it goes wrong:

```json
 {
      "apiVersion": "[variables('apiVersionDefault')]",
      "copy": {
        "count": "[sub(variables('windowspoolCount'), variables('windowspoolOffset'))]",
        "name": "vmLoopNode"
      },
      "dependsOn": [
        ...
      ],
      "location": "[variables('location')]",
      "name": "[concat(variables('windowspoolVMNamePrefix'), copyIndex(variables('windowspoolOffset')))]",
      "properties": {
       ...
        "osProfile": {
 ...
          "customData": ... variables('vnetSubnetID') ...
 },
```
How to fix it
Change variables('subnet') to variables('')
**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment] 2018-04-02 17:19
Closing because this is a duplicate of #1767

**Closed by CecileRobertMichon** 2018-04-02 17:19 UTC
Labels: kind/bug
