### ISSUE TITLE
Windows Node UNEXPECTED_KERNEL_MODE_TRAP vfpext.sys

### ISSUE THREAD

**Issue by y325A** [Azure/acs-engine#3798] opened 2018-09-05 10:11 UTC
**Is this a request for help?**:
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue

---

**What version of acs-engine?**:
0.21.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s 1.10.7
Windows Server 2016 17134

**What happened**:
Blue screen of death OS crash when scheduling a large number of pods simultaneously.
```
Your PC ran into a problem and needs to restart.
If you call a support person, give them this info:
UNEXPECTED_KERNEL_MODE_TRAP

vfpext.sys

0x0000000000000008
0xFFFFAD8068589EF0
0xFFFFC2057182AFA0
0xFFFFF80F422CA66F
```

**How to reproduce it** (as minimally and precisely as possible):
ACS template and Dockerfiles below. It only appears to happen with this particular Dockerfile below (which seems weird, I have other Dockerfiles that don't cause crashes). Scale deployment up to 10 replicas and wait for crash.

```
{
    "apiVersion": "vlabs",
    "properties": {
        "orchestratorProfile": {
            "orchestratorType": "Kubernetes",
            "orchestratorRelease": "1.10",
            "kubernetesConfig": {
                "addons": [
                    {
                        "name": "kubernetes-dashboard",
                        "enabled": false
                    }
                ],
                "apiServerConfig": {
                    "--token-auth-file": "/etc/kubernetes/token.csv"
                }
            }
        },
        "masterProfile": {
            "count": 1,
            "dnsPrefix": "",
            "vmSize": "Standard_B2ms",
            "customFiles": [
                {
                    "source": "",
                    "dest": "/etc/kubernetes/token.csv"
                }
            ]
        },
        "agentPoolProfiles": [
            {
                "name": "windowspool",
                "count": 1,
                "vmSize": "Standard_B2ms",
                "availabilityProfile": "AvailabilitySet",
                "osType": "Windows",
                "osDiskSizeGB": 127,
                "storageProfile": "StorageAccount"
            }
        ],
        "windowsProfile": {
            "adminUsername": "",
            "adminPassword": "",
            "windowsPublisher": "MicrosoftWindowsServer",
            "windowsOffer": "WindowsServerSemiAnnual",
            "windowsSku": "Datacenter-Core-1803-with-Containers-smalldisk"
        },
        "linuxProfile": {
            "adminUsername": "",
            "ssh": {
                "publicKeys": [
                    {
                        "keyData": ""
                    }
                ]
            }
        },
        "servicePrincipalProfile": {
            "clientId": "",
            "secret": ""
        }
    }
}
```

Base Dockerfile:
```
FROM microsoft/dotnet-framework@sha256:c2586af354bc76c2f431e3d6584bd38c277b896a6a5b07dc0042b4ff7480956f

RUN powershell -Command \
    New-ItemProperty -Path HKLM:\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters -Name MaxNegativeCacheTtl -PropertyType DWord -Value 0

COPY ./helpers /helpers
```

App Dockerfile:
```
ARG REGISTRY

FROM ${REGISTRY}/**my image and tag derived from above Dockerfile**

ARG CONFIGURATION

ENTRYPOINT powershell.exe C:\helpers\install-certs.ps1 && C:\application\myapp.exe

COPY ./bin/${CONFIGURATION} /application
```

**Anything else we need to know**:
I have a QA env where I can fairly reliably repro the issue if anyone wants me to test anything.

**Comment by PatrickLang** [comment] 2018-09-05 17:26
This is fixed in an update that's not part of the VM yet. You can work around it using this in your apimodel:

```json
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.11"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "plang0607a",
      "vmSize": "Standard_D2_v3"
    },
    "agentPoolProfiles": [
	    {
		"name": "windowspool",
		"count": 2,
		"vmSize": "Standard_D2_v3",
		"availabilityProfile": "AvailabilitySet",
		"osType": "Windows",
		"osDiskSizeGB": 127,
		"extensions": [
	    {
			"name": "windows-patches"
		    }
		]
	    },
	    {
		"name": "linuxpool",
		"count": 2,
		"vmSize": "Standard_D2_v2",
		"availabilityProfile": "AvailabilitySet",
		"osType": "Linux"
	    }
    ],
    "windowsProfile": {
	    "adminUsername": "",
	    "adminPassword": "",
	    "windowsPublisher": "MicrosoftWindowsServer",
	    "windowsOffer": "WindowsServerSemiAnnual",
	    "windowsSku": "Datacenter-Core-1803-with-Containers-smalldisk"
     },
    "extensionProfiles": [
          {
	    "name": "windows-patches",
	    "version": "v1",
            "extensionParameters": "'https://privatepatches.blob.core.windows.net/hotfix/Windows10.0-KB999999-x64-InstallForTestingPurposesOnly.exe?se=2018-09-17T00%3A09%3A48Z&sp=r&sv=2017-07-29&sr=b&sig=SoWlPWDCIsyuO2xKvPRgeK90U/9k/K6B4wkdFT3Jgpg%3D', 'http://download.windowsupdate.com/c/msdownload/update/software/secu/2018/08/windows10.0-kb4343909-x64_f931af6d56797388715fe3b0d97569af7aebdae6.msu'"
    }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}
```

**Comment by PatrickLang** [comment] 2018-09-05 17:30
If that doesn't work - please open a support ticket and they can provide a private patch.

cc @daschott

**Comment by tonyschollum** [comment] 2018-09-21 08:56
Hi @PatrickLang ,

I have had the same issue today. To apply your suggestion above do I need to completely delete the cluster and deploy a new one or is there some other process to this?

Thanks for your help

**Comment by daschott** [comment] 2018-09-21 18:04
@tonyschollum you need to open a support ticket with Microsoft/Azure, else there should be a public KB coming out soon (no earlier than mid-November unfortunately.) Will loop back here once it is posted. 

Either option does not require you to delete your cluster. You will be required to install an update and reboot each one of your nodes however. If you have a new cluster you are trying to create, you can also apply the patches automatically using [Windows Patching Extension](https://github.com/Azure/acs-engine/blob/42ff7c17fd3577c0e2dc181fffb6a7fead2f85dc/extensions/windows-patches/README.md#Example)

**Comment by PatrickLang** [comment] 2018-09-21 20:02
If you have a fix from Microsoft support, you can follow the steps here to get access to your existing nodes with Remote Desktop. Then you can post the fix in a storage account, download and install it on the Windows nodes

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/troubleshooting.md#connecting-to-windows-nodes

Using the Windows patching extension is definitely easier for new clusters.

**Comment by sylus** [comment] 2018-11-27 05:20
Ah yeah unfortunately the msu doesn't successfully install but thanks for the help.

I did notice that Datacenter-Core-1809-with-Containers-smalldisk is now on the list of published images and is the equivalent build of Windows 2019. Thinking this would have the fix?

Only issue currently against that SKU is:

```sh
Events:
  Type     Reason                  Age               From                   Message
  ----     ------                  ----              ----                   -------
  Normal   Scheduled               5m                default-scheduler      Successfully assigned default/ndmdotnet-admintool-5fb787d6f6-zws7l to 16822k8s9010
  Warning  FailedCreatePodSandBox  3s (x24 over 5m)  kubelet, 16822k8s9010  Failed create pod sandbox: rpc error: code = Unknown desc = failed pulling image "kubletwin/pause": Error response from daemon: repository kubletwin/pause not found: does not exist or no pull access
```

**Comment by daschott** [comment] 2018-11-27 20:32
No, this issue still persists on Windows Server 1809 until a hotfix is released (ETA late January). The official hotfix is available
now for WS1803: https://support.microsoft.com/en-us/help/4467682/windows-10-update-kb4467682
Can you try it? What errors are you seeing?

For DataCenter-Core-1809, you are correct I also noticed an issue in acs-engine because of the move to the new container registry. You need to build `kubletwin/pause` image by editing the Dockerfile in C:\k to annotate the
`mcr.microsoft.com/windows/nanoserver:1809` image
and build it as `docker build -t kubletwin/pause .`

Once you move to azure-CNI 1.0.14, please also double-check that the service CIDR in the 10-azure.conflist isn't set to 10.0.0.0/8 but 10.0.0.0/16. You can check the service CIDR using
`kubectl cluster-info dump | grep -i service-cluster-ip-range`

If you're still having trouble with DNS, one workaround is to remove the entry for the 163.x.y.z nameserver. For some reason it isn't reaching it on my cluster. I'm not from the Azure networking team but I found that worked for all the typical networking flows then.

**Comment by daschott** [comment] 2018-11-27 20:32
@y325A can you also please use https://support.microsoft.com/en-us/help/4467682/windows-10-update-kb4467682 and confirm whether the issue is resolved?

**Comment by sylus** [comment] 2018-11-27 21:20
@daschott thanks so much for your guidance just out of curiousity I was looking at the changelog for https://support.microsoft.com/en-us/help/4467682/windows-10-update-kb4467682 do you know which line in particular talks about this problem as don't see it listed.

**Comment by daschott** [comment] 2018-11-27 22:04
I don't think it's explicitly written there, the changelogs aren't exhaustive and don't always reflect all the fixes unfortunately... But looking at the bug this is the official KB article that contains a complete patch for the BSoD referenced by @y325A here.

**Comment by sylus** [comment] 2018-11-28 04:08
Ah @daschott your awesome, the msu you referenced does work at least so far and haven't seen the issue for the past hour or so, going to leave on overnight and test. Appreciate you taking the time :D

**Comment by sylus** [comment] 2018-12-05 19:08
Hey @daschott I think acs-engine now defaults to 1809 so to be able to apply the patch since for 1809 won't be available for a month, should I just revert the generated azuredeploy to call the older 1803 image?

**Comment by sylus** [comment] 2018-12-10 16:52
Hey @daschott @PatrickLang the update msi patch is no longer hosted. Do you know how I can get this update again? Not sure why it was removed.

**Comment by daschott** [comment] 2018-12-11 23:10
@sylus, yes it seems like the KB was pulled down because there were some other changes included in the package which introduced regressions. Can you use the new 12B release, it should contain all the fixes from the previous KB without regressions:
https://support.microsoft.com/en-us/help/4471324

**Comment by sylus** [comment] 2018-12-12 02:16
Ah thanks so much @daschott your awesome :)

**Comment by PatrickLang** [comment] 2018-12-18 21:10
Alright, closing since https://support.microsoft.com/en-us/help/4471324/windows-10-update-kb4471324 is released.

**Closed by PatrickLang** 2018-12-18 21:10 UTC
Labels: kind/bug, orchestrator/k8s, windows

**Comment by daschott** [comment] 2019-01-11 21:02
For WS2019, this should come out on 01/22 as KB4476976.
