### ISSUE TITLE
CSE failure during deploy because 8.8.8.8 port 53 is blocked in our vnet

### ISSUE THREAD

**Issue by grenzr** [Azure/acs-engine#3502] opened 2018-07-18 14:05 UTC
**Is this a request for help?**:

YES

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

0.19.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes 1.11.0 (Azure CNI)

**What happened**:

When deploying acs-engine into a vnet, the CSE fails to complete, because its doing an outbound internet check by testing access to 8.8.8.8 on port 53.

https://github.com/Azure/acs-engine/pull/3083/files

This will not work in our case, because our enterprise admin has enforced restrictions on our account such that we have to use an internal DNS server for all resolutions (all other port 53 access is blocked).

**What you expected to happen**:

Why not do an nc to microsoft.com port 443 instead? That will test internet connectivity and DNS resolution in one. Can anyone give a good reason why its done specifically this way?

**How to reproduce it** (as minimally and precisely as possible):

Block access to 8.8.8.8 port 53 in your vnet, and only allow access to Azure DNS servers.

**Anything else we need to know**:

**Comment by PHaigh-tw** [comment] 2018-07-18 14:41
It might be better even still to target a comminications check against a URL or server that's used subsequently in the build.   For corporate environments in which we lock down all access except what's required, we would reject an outbound request to www.microsoft.com as it's not required for the script to execute, other than the check.

**Comment by CecileRobertMichon** [comment] 2018-08-13 21:02
Duplicate of https://github.com/Azure/acs-engine/issues/3563, fixed with https://github.com/Azure/acs-engine/pull/3570

**Closed by CecileRobertMichon** 2018-08-13 21:02 UTC
