### ISSUE TITLE
Kubernetes Master etcd died when running out of disk space

### ISSUE THREAD

**Issue by jimmystridh** [Azure/acs-engine#382] opened 2017-03-09 16:01 UTC
I just had my master die because it ran out of diskspace in /

It was actually etcd that died

> etcd[54776]: failed to allocate space when creating new wal file (no space left on device)
> etcd[54776]: open wal error: no space left on device
> systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE

and a `df -h` gave me:

> dev/sda1        29G   29G     0 100% /

when I went into /var to run u -h --max-depth=1 then all of sudden df -h gives me

> /dev/sda1        29G  4.7G   24G  17% /

this was a minute after the above command. Restarting etcd seems to have everything back to normal.

The disk became full approx 34 hours ago.

Any ideas why this would happen ? Is monitoring the disk space on the masters something we should do ?

**Comment by jimmystridh** [comment] 2017-03-09 16:05
Seems to be about the same issue as #350 though I have no idea what caused the space to be released all of a sudden

**Comment by anhowe** [comment] 2017-03-09 16:26
Are you able to update your cluster using the code found in https://github.com/Azure/acs-engine/pull/373.    Without looking at your system further, I suspect the log files under /var/lib/docker/containers/ were purged, bringing you back down to 17%. I'm going to close as duplicate of #350.

**Closed by anhowe** 2017-03-09 16:26 UTC
