### ISSUE TITLE
Customize allocation of ephemeral disk space on DC/OS

### ISSUE THREAD

**Issue by rozele** [Azure/acs-engine#834] opened 2017-06-21 20:44 UTC
**Is this a request for help?**:
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

FEATURE REQUEST - It would be nice to have a way to customize the allocation of the ephemeral disk to `/var/lib/mesos`, `/var/lib/docker`, and `/tmp`.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
DC/OS 1.9

**What happened**:
On DC/OS, the ephemeral disk is split proportionally between `/var/lib/docker`, `/var/lib/mesos`, and `/tmp`. The proportions are 45%, 45%, and 10%, respectively.

**What you expected to happen**:
I'd like a way to customize the proportions of the ephemeral disk that are allocated to `/var/lib/docker` and `/var/lib/mesos`.

**How to reproduce it** (as minimally and precisely as possible):
1) Deploy a DC/OS ACS template
2) ssh to master node
3) run `sudo fdisk -l` and see /dev/sdb[1|2|3] and allocated sizes

**Anything else we need to know**:
No.

**Comment by jmspring** [comment] 2017-06-21 20:51
Ideally this could be defined per agent pool.  The rational for this request is that in discussions with a customer (I've heard it from another in passing as well) they are using something like Cassandra on AWS with ephemeral disk only.

The current work around is to modify the generated azuredeploy.json file.

**Comment by rozele** [comment] 2017-06-22 14:54
It looks like this is actually a dupe of https://github.com/Azure/acs-engine/issues/133

**Comment by JackQuincy** [comment] 2017-06-22 17:04
It is a dupe. If we were to do this we would want something similar to how we have kubernetesConfig on the orchestratorProfile that would allow us to do things like this.

**Comment by rozele** [comment] 2017-06-22 17:51
@JackQuincy I'm actually not finding that the volumes are necessarily landing on the ephemeral disks as well. It's trivial enough to edit these splits, but it seems like, based on the agent pool, only one of the 3 ephemeral allocations is actually assigned. E.g.,
* only /var/lib/mesos is on ephemeral on private agents
* only /var/lib/docker is on ephemeral on master

That means that 55% of the ephemeral disk is not being used on nodes in these pools...

**Comment by JackQuincy** [comment] 2017-06-22 18:00
hmm... that would be strange as we specify all three in the same way. can you copy the output that makes you think that is true?

**Comment by rozele** [comment] 2017-06-22 18:16
```
azureuser@dcos-master-83165892-0:~$ df -h /var/lib/mesos
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        30G  3.1G   26G  11% /
```
```
azureuser@dcos-master-83165892-0:~$ df -h /var/lib/docker
Filesystem      Size  Used Avail Use% Mounted on
/dev/sdb2        45G   52M   42G   1% /var/lib/docker
```

**Comment by anhowe** [comment] 2017-06-23 02:50
I recommend filing this as an upstream issue for https://github.com/dcos/dcos.  Basically Mesosphere has built these templates and added that ratio and logic.

This is a duplicate of #133.

**Comment by jmspring** [comment] 2017-06-23 06:09
Anthony - 

See the email I sent you.  I'll talk with Mesosphere about this next week.  I'm also thinking a PR that allows for customization via acs-engine makes sense on a per agent pool basis and I'll do this work.

We can chat here or email about such.

I understand your point, but control on resource allocation given different vm skus (L-series up to 600+gig ephemeral SSD) and different workloads makes sense as something we should enable.

**Comment by mboersma** [comment] 2019-01-10 18:21
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine). 

Please follow up at [dcos-engine](https://github.com/Azure/dcos-engine) for any Mesos/DCOS issues.

**Closed by mboersma** 2019-01-10 18:21 UTC
Labels: orchestrator/dcos, priority/P2
