### ISSUE TITLE
acs-engine scaling failed with error [segmentation violation code=0x1 addr=0x8 pc=0x11aa9be]

### ISSUE THREAD

**Issue by saromba** [Azure/acs-engine#3337] opened 2018-06-22 07:09 UTC
**Is this a request for help?**: 
Yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):ISSUE

---

**What version of acs-engine?**:0.18.9

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes (1.9.8)

**What happened**:

[36mINFO[0m[0000] validating...                                

[36mINFO[0m[0001] Name suffix: %s 15892004                     
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x11aa9be]

goroutine 1 [running]:
github.com/Azure/acs-engine/cmd.(*scaleCmd).run(0xc420386000, 0xc42037c6c0, 0xc42035f320, 0x0, 0x12, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:224 +0x38e
github.com/Azure/acs-engine/cmd.newScaleCmd.func1(0xc42037c6c0, 0xc42035f320, 0x0, 0x12, 0x0, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:69 +0x52
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc42037c6c0, 0xc42035f200, 0x12, 0x12, 0xc42037c6c0, 0xc42035f200)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f1
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42032f8c0, 0xc42037c6c0, 0xc42037c480, 0xc42037c240)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x2fe
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42032f8c0, 0xc42000c018, 0x0)
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
	/Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:12 +0x74

**What you expected to happen**:
Correct scaling of the cluster

**How to reproduce it** (as minimally and precisely as possible):
/root/deploy/acs-engine/acs-engine scale --auth-method client_secret --client-id $AZURE_CLIENT_ID --client-secret $AZURE_CLIENT_SECRET --subscription-id $AZURE_SUBSCRIPTION_ID --resource-group $AZURE_RESOURCEGROUP --location westeurope --deployment-dir tmpDir --new-node-count $NODE_COUNT --master-FQDN $AZURE_RESOURCEGROUP.westeurope.cloudapp.azure.com

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment] 2018-06-22 16:29
Hi @saromba, could share you cluster configuration json (after removing secrets)? Did you manually change anything in the generated azuredeploy.json before deploying?

**Comment by CecileRobertMichon** [comment] 2018-06-22 16:30
Here's similar issue https://github.com/Azure/acs-engine/issues/2649 that was fixed a while ago in case that helps.

**Comment by saromba** [comment] 2018-06-25 06:50
Hi @CecileRobertMichon: Which file do you need? There are many files during the provisioning. 
How is it called?

**Comment by CecileRobertMichon** [comment] 2018-06-25 18:38
@saromba `apimodel.json` but make sure you remove all secrets

**Comment by saromba** [comment] 2018-07-23 06:53
@CecileRobertMichon 
Hi, something new here?

Regards,
saromba

**Comment by CecileRobertMichon** [comment] 2018-07-30 20:55
@saromba no update yet, I wasn't able to repro and then went on vacation. I'll try to give it another look this week. Did you by any chance scale or upgrade your cluster previously? Or was this cluster in its original state when you attempted to scale?

**Comment by saromba** [comment] 2018-08-20 05:55
Hi @CecileRobertMichon,

we fixed that ourselves, scaling is now possible again...
See that "vmTags stuff" -> Cmd/scale.go_

    ndexToVM := make(map[int]string)
    if sc.agentPool.IsAvailabilitySets() {
       for vmsListPage, err := sc.client.ListVirtualMachines(ctx, sc.resourceGroupName);     vmsListPage.NotDone(); err = vmsListPage.Next() {
      if err != nil {
         return errors.Wrap(err, "failed to get vms in the resource group")
      } else if len(vmsListPage.Values()) < 1 {
         return errors.New("The provided resource group does not contain any vms")
      }
      for _, vm := range vmsListPage.Values() {
         vmTags := vm.Tags
         poolName := *vmTags["poolName"]
         nameSuffix := *vmTags["resourceNameSuffix"]

         //Changed to string contains for the nameSuffix as the Windows Agent Pools use only a substring of the first 5 characters of the entire nameSuffix
         if err != nil || !strings.EqualFold(poolName, sc.agentPoolToScale) || !strings.Contains(sc.nameSuffix, nameSuffix) {
            continue
         }

         osPublisher := vm.StorageProfile.ImageReference.Publisher
         if osPublisher != nil && strings.EqualFold(*osPublisher, "MicrosoftWindowsServer") {



    }
    } else {
       for vmssListPage, err := sc.client.ListVirtualMachineScaleSets(ctx, sc.resourceGroupName); vmssListPage.NotDone(); vmssListPage.Next() {
      if err != nil {
         return errors.Wrap(err, "failed to get vmss list in the resource group")
      }
      for _, vmss := range vmssListPage.Values() {
         vmTags := vmss.Tags
         poolName := *vmTags["poolName"]
         nameSuffix := *vmTags["resourceNameSuffix"]

         //Changed to string contains for the nameSuffix as the Windows Agent Pools use only a substring of the first 5 characters of the entire nameSuffix
         if err != nil || !strings.EqualFold(poolName, sc.agentPoolToScale) || !strings.Contains(sc.nameSuffix, nameSuffix) {
            continue

Regards,
saromba

**Comment by CecileRobertMichon** [comment] 2018-08-20 16:04
Hi @saromba, I'm glad to hear that you are unblocked. Was the root cause that the VM tags were missing? How can we fix this so that others don't run into the same issue?

**Comment by ryanlovett** [comment] 2018-09-04 20:31
@CecileRobertMichon Based on @saromba's comment, I cheched our VM tags and found both poolName and resourceNameSuffix present.

**Comment by CecileRobertMichon** [comment] 2018-09-04 20:35
@ryanlovett can you please share your apimodel and exact steps you took so I can try and repro?

**Comment by ryanlovett** [comment] 2018-09-04 20:37
We had manually added a non-cluster VM to the resource group and this VM did not have those tags. I just manually added them and acs-engine hasn't crashed yet.

I think scale.go should check for whether the poolName and resourceNameSuffix tags exist before trying to reference them. I know nothing about go, otherwise I'd create a PR.

**Comment by CecileRobertMichon** [comment] 2018-09-04 20:44
@ryanlovett agreed, we have an issue tracking this problem at https://github.com/Azure/acs-engine/issues/3663. I will close this one.

**Closed by CecileRobertMichon** 2018-09-04 20:44 UTC
Labels: feature/scale

**Comment by ryanlovett** [comment] 2018-09-04 20:49
Great, thanks!
