### ISSUE TITLE
Kubernetes orchestrator to have support for docker versions greater than 1.18

### ISSUE THREAD

**Issue by akhileshthipparthi** [Azure/acs-engine#3331] opened 2018-06-21 20:09 UTC
**Is this a request for help?**:
Request
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Feature
---

**What version of acs-engine?**:
v0.18.9
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:
acs-engine for K8s doesnt have support for latest docker versions.

**What you expected to happen**:

acs-engine for K8s to have support for docker versions greater than 1.18

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by CecileRobertMichon** [comment] 2018-06-22 16:24
This is a duplicate of https://github.com/Azure/acs-engine/issues/2876

**Closed by CecileRobertMichon** 2018-06-22 16:24 UTC
