### ISSUE TITLE
acs-engine 0.12.1 scale failing for windows nodes

### ISSUE THREAD

**Issue by campbelldgunn** [Azure/acs-engine#2107] opened 2018-01-19 21:13 UTC
**Is this a request for help?**: NO

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.12.1

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.1

**What happened**:
Trying to scale out Windows nodes in a windows pool from 3 to 5. using the following command:
```
./acs-engine scale --subscription-id <REDACTED> \
--resource-group "<REDACTED>" --location westus \
--deployment-dir _output/<REDACTED> --new-node-count 5 \
--node-pool windowspool1 --master-FQDN <REDACTED>
```
It fails with the error below and only have 3 nodes instead of 5 nodes for the windows pool.

**What you expected to happen**:
Have 5 windows nodes instead of 3.

**How to reproduce it** (as minimally and precisely as possible):
Execute the above command on MacOSX
Get the following error message:
```
INFO[0000] validating...                                
INFO[0002] Name suffix: 33247490                        
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Azure/acs-engine/cmd.(*scaleCmd).run(0xc4205c2780, 0xc42054a480, 0xc4200fa1c0, 0x0, 0xe, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:213 +0x21c5
github.com/Azure/acs-engine/cmd.newScaleCmd.func1(0xc42054a480, 0xc4200fa1c0, 0x0, 0xe, 0x0, 0x0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/cmd/scale.go:66 +0x52
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).execute(0xc42054a480, 0xc4200fa0e0, 0xe, 0xe, 0xc42054a480, 0xc4200fa0e0)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc42055f200, 0xc42055fd40, 0xc42055f8c0, 0xc42055f680)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/Azure/acs-engine/vendor/github.com/spf13/cobra.(*Command).Execute(0xc42055f200, 0xc42059df68, 0x205a1a5)
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/vendor/github.com/spf13/cobra/command.go:685 +0x2b
main.main()
        /Users/jackfrancis/work/src/github.com/Azure/acs-engine/main.go:9 +0x2f
```
**Anything else we need to know**:
The cluster is a mixed cluster, meaning it contains a windows and linux pool. Prior to running the acs-engine scale command to increase the windows pool, the same command completed successfully for the linux pool going from 4 to 10 nodes.

**Comment by CecileRobertMichon** [comment] 2018-01-19 23:30
Closing this issue as it is a duplicate of #1972

**Closed by CecileRobertMichon** 2018-01-19 23:30 UTC
