### ISSUE TITLE
[k8s] Custom Labels for Agent Pools

### ISSUE THREAD

**Issue by tekmaven** [Azure/acs-engine#332] opened 2017-02-28 16:40 UTC
I need to assign custom labels to nodes in agent pools.  I think if something similar to how #138 was implemented for DCOS was ported for use in k8s, that would be a very flexible solution.  It would also cover #139.

**Comment by anhowe** [comment] 2017-03-08 20:28
This is a duplicate of https://github.com/Azure/acs-engine/issues/139.  I updated the title to make this more clear

**Closed by anhowe** 2017-03-08 20:28 UTC
