### ISSUE TITLE
Error in dnsPrefix in 0.17.1

### ISSUE THREAD

**Issue by ptrstpp950** [Azure/acs-engine#3058] opened 2018-05-23 18:32 UTC
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
0.17.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
I run a command from the [tutorial](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md). When my json contains:
```
"masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2"
    },
```
The error appears:
>INFO[0000] Error returned by LoadContainerService: missing Properties.MasterProfile.DNSPrefix
>FATA[0000] failed to load apimodel: %s error parsing the api model: missing Properties.MasterProfile.DNSPrefix

When I added `"dnsPrefix": "something",` and run example command with dns prefix set I got another error:
> FATA[0035] invalid configuration: the apimodel masterProfile.dnsPrefix and --dns-prefix were both specified 

**What you expected to happen**:
A success without an error :)

**What else**
Also, there is a problem with not filling 
```
"ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
```

>INFO[0000] Error returned by LoadContainerService: Namespace Properties.LinuxProfile.SSH.PublicKeys is not caught, Key: 'Properties.LinuxProfile.SSH.PublicKeys' Error:Field validation for 'PublicKeys' failed on the 'required' tag
>FATA[0000] failed to load apimodel: %s error parsing the api model: Namespace Properties.LinuxProfile.SSH.PublicKeys is not caught, Key: 'Properties.LinuxProfile.SSH.PublicKeys' Error:Field validation for 'PublicKeys' failed on the 'required' tag

**Comment by CecileRobertMichon** [comment] 2018-05-23 18:39
Closing as this is a duplicate of #3051

**Closed by CecileRobertMichon** 2018-05-23 18:39 UTC
