### ISSUE TITLE
etcd fails to start at starting time

### ISSUE THREAD

**Issue by skuda** [Azure/acs-engine#1481] opened 2017-09-24 14:39 UTC
**Is this a request for help?**:
NO

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

**What version of acs-engine?**:
0.6.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.5

**What happened**:
After restarting master node etcd doesn't start correctly.

**What you expected to happen**:
etcd starts correctly.

**How to reproduce it** (as minimally and precisely as possible):
For me it was as easy as install the cluster and reboot the master node.

**Anything else we need to know**:

This is the systemd status etcd output after reboot:
```
● etcd.service - etcd - highly-available key value store
   Loaded: loaded (/lib/systemd/system/etcd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-09-24 13:47:39 UTC; 3min 45s ago
     Docs: https://github.com/coreos/etcd
           man:etcd
  Process: 1193 ExecStart=/usr/bin/etcd $DAEMON_ARGS (code=exited, status=1/FAILURE)
 Main PID: 1193 (code=exited, status=1/FAILURE)

Sep 24 13:47:39 k8s-master-42737137-0 systemd[1]: Starting etcd - highly-available key value store...
Sep 24 13:47:39 k8s-master-42737137-0 systemd[1]: etcd.service: Main process exited, code=exited, status=1/FAILURE
Sep 24 13:47:39 k8s-master-42737137-0 systemd[1]: Failed to start etcd - highly-available key value store.
Sep 24 13:47:39 k8s-master-42737137-0 systemd[1]: etcd.service: Unit entered failed state.
Sep 24 13:47:39 k8s-master-42737137-0 systemd[1]: etcd.service: Failed with result 'exit-code'.
```

I found the problem checking journalctl:
```
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: etcd Version: 2.2.5
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: Git SHA: Not provided (use ./build instead of go build)
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: Go Version: go1.6.2
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: Go OS/Arch: linux/amd64
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: listening for peers on http://10.240.255.5:2380
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: listening for client requests on http://10.240.255.5:2379
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: listening for client requests on http://127.0.0.1:2379
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: stopping listening for client requests on http://127.0.0.1:2379
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: stopping listening for client requests on http://10.240.255.5:2379
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: stopping listening for peers on http://10.240.255.5:2380
Sep 24 13:47:39 k8s-master-42737137-0 etcd[1193]: cannot access data directory: open /var/lib/etcddisk/.touch: permission denied
```

After checking that I could start manually etcd without problems after I ssh'ed the master node I fixed the problem locally using:
```
mkdir -p /etc/systemd/system/etcd.service.d
(
cat << EOF
[Unit]
Requires=var-lib-etcddisk.mount
After=var-lib-etcddisk.mount
EOF
) > /etc/systemd/system/etcd.service.d/wait-folder.conf
```

BTW, taking a look to why is being mounted that way I found:
https://github.com/Azure/acs-engine/issues/636
the related pr:
https://github.com/Azure/acs-engine/pull/661
and the related upstream bug:
https://bugs.launchpad.net/cloud-init/+bug/1692093

This bug seems to be already fixed in recent versions of Ubuntu 16.04 Xenial, I upgraded the package in the master box and I got:
```
oot@k8s-master-42737137-0:/home/azureuser# dpkg -l | grep "cloud-init "
ii  cloud-init                         0.7.9-233-ge586fe35-0ubuntu1~16.04.1       all          Init scripts for cloud instances
```

Maybe is time for a change to try to come back to use cloud-init?

Miguel.

**Comment by CecileRobertMichon** [comment] 2017-10-23 20:18
Unable to reproduce the issue in v0.8.0. This should have been fixed by PR #1539 and #1521. An issue has been created to revert PR #661 since the cloud-init bug was fixed in the latest Ubuntu image (#1643).

**Closed by CecileRobertMichon** 2017-10-23 20:18 UTC
