### ISSUE TITLE
Offer binaries in releases tab

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/acs-engine#93] opened 2016-11-14 23:55 UTC
A fairly easy thing to do in via Travis-CI. [[example](https://github.com/Azure/azure-extensions-cli/blob/42a13c77a73ac87b253d421d6043836f6a5a629a/.travis.yml#L14-L25)]

This would make installation experience a ton easier.

update: Related: #55.

**Comment by anhowe** [comment] 2017-01-23 22:46
This is duplicate of #55.  I've udpated #55 with this info.

**Closed by anhowe** 2017-01-23 22:46 UTC
Labels: enhancement, kind/documentation, priority/P1
