### ISSUE TITLE
Regression to azure network plugin introduced by latest CIDR changes

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#493] opened 2017-04-12 17:59 UTC
@ashb @ofiliz - the latest CIDR changes have broken the azure network plugin.  Deploying a standard template repros crash looping of the dns and dashboard processes.

The logs of DNS show the following error:

E0412 04:27:57.862786       1 reflector.go:214] pkg/dns/dns.go:156: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout

**Comment by ashb** [comment] 2017-04-12 18:02
That normally appears at the start of the log for a few times. Just to confirm: that just keeps happening?

**Comment by ofiliz** [comment] 2017-04-13 19:24
If anyone actively investigating this? If you can't figure it out, please undo this change.

**Comment by ofiliz** [comment] 2017-04-14 01:07
We've discovered that the azure-vnet CNI plugin suffers from a problem similar to #439. I'll fix that first, then check if it fixes this problem as well.

**Comment by ashb** [comment] 2017-04-19 12:33
Is there anything I can do to help this along? It's not affecting me but I'm keen to not see my previous merge backed out :)

**Comment by rocketraman** [comment] 2017-04-19 13:18
I'm having the same issue. I don't see the error message shown by @anhowe on my setup, but the behavior is exactly the same -- the DNS and dashboard pods are in a crash loop (several hours now).

@ashb Here is what I am doing -- perhaps you can repro in your environment:

1. Create a custom vnet using [this template](https://github.com/Azure/acs-engine/blob/master/examples/vnet/vnetarmtemplate/azuredeploy.kubernetes.json) -- modify the `addressPrefix` in two places to 10.10.0.0/16.

2. Create an engine template with the following `orchestratorProfile`:
```
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "clusterCidr": "10.10.0.0/16",
        "serviceCidr": "10.11.0.0/16",
        "dnsServiceIP": "10.11.255.1"
      }
    },
```
and `"firstConsecutiveStaticIP": "10.10.255.239"`. Update servicePrincipal info as necessary.

3. Generate the deployment templates and deploy them to the same RG as the custom vnet.

The other thing I would note, which may or may not be related, is that the [temporary workaround](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md) for the CustomVNET (step 7) to add a `routeTable` after deployment makes things even worse: without the temporary workaround the nodes are at least in Ready state (though with the crash loop described above). With the temporary workaround, all nodes drop to NotReady state.

**Comment by ashb** [comment] 2017-04-19 13:23
@rocketraman That's curious cos I've been building them on and off like that for 3 days. And I don't have crash loops. Let me update my acs-engine to master and see if I can repro.

**Comment by ashb** [comment] 2017-04-19 14:06
@rocketraman Can you check in the logs of the controller-manager pod on your master? OD you see lots of errors like `routecontroller.go:160] Could not create route ....`?

**Comment by ashb** [comment] 2017-04-19 14:23
I'm testing something, the problem might be that the subnet address range is as large as vnet, and k8s/azure route table gets confused. I'm trying you example with a /24 on the subnet address prefix rather than /16 for both prefixes. The example might be broken.

**Comment by rocketraman** [comment] 2017-04-19 14:29
> @rocketraman Can you check in the logs of the controller-manager pod on your master? OD you see lots of errors like routecontroller.go:160] Could not create route ....?

Yup:

```
$ kubectl logs --namespace=kube-system kube-controller-manager-k8s-master-30143214-0 | strings | grep "Could not create route" | wc -l
807
```

**Comment by ashb** [comment] 2017-04-19 16:19
Okay, my findings (through spinning up and about about 10 clusters and getting a bit confused):

- Without a subnet configured the heapster and dashboard pods stayed in the "Pending" state
- That error will show up as long as as there is no route table associated with the subnet. Within a few seconds of associating the routetable to the subnet the errors disappeared and the routes were created.
- To have it all working reliably the subnet addressPrefix needs to be _smaller_ than the whole vnet.

I think the last point is the key takeaway. @rocketraman can you try with that change? Without it one of the nodes will get assigned for its pod IP space 10.10.0.0/24, which will lead to an IP clash - the agent VMs will likely have IPs of 10.10.0.4, .5, and .6 (if there are three. say.)

My working configs are:

apimodel:
```json
      "kubernetesConfig": {
        "kubernetesImageBase": "gcrio.azureedge.net/google_containers/",
        "networkPolicy": "none",
        "dnsServiceIP": "192.168.1.10",
        "serviceCidr": "192.168.1.0/24",
        "clusterCidr": "10.10.0.0/16"
      }
```

vnet settings:
```json
  "addressSpace": {
    "addressPrefixes": [
      "10.10.0.0/16"
    ]
  },
  "subnets": [
    {
      "addressPrefix": "10.10.255.0/24",
    }
  ]
```

**Comment by rocketraman** [comment] 2017-04-20 14:32
@ashb Unfortunately I'm already using 192.168.1.0/24 elsewhere and even though the subnet cidr is non-routable, I want to avoid confusion. Given that, if I understand this correctly, I need to split up my VNET address space, say 10.10.0.0/16 into three non-overlapping subnets -- one for Kubernetes itself, one for the cluster, and one for services.

I'd like to try the following -- let me know if you think this should work:

10.10.0.0/17 - cluster subnet (32766 ips)
10.10.128.0/18 - service subnet (16382 ips)
10.10.192.0/19 - Kubernetes subnet (8190 ips)

**Comment by ashb** [comment] 2017-04-20 14:42
@rocketraman Assuming that cluster subnet is set as the `clusterCidr` parameter, and that Kubernetes subnet is the subnet's addressPrefix, and that addressPrefix for the whole vnet stays as 10.10.0.0/16, then yes I think that should work.

**Comment by rocketraman** [comment] 2017-04-20 15:08
> @rocketraman Assuming that cluster subnet is set as the clusterCidr parameter, and that Kubernetes subnet is the subnet's addressPrefix, and that addressPrefix for the whole vnet stays as 10.10.0.0/16, then yes I think that should work.

Perfect, giving that a shot now.

**Comment by rocketraman** [comment] 2017-04-20 15:25
I'm also assuming the firstConsecutiveStaticIp for the master node falls in the 10.10.192.0/19 range I defined for Kubernetes (the vnet's Kubernetes subnet address prefix). The documentation for this stuff really needs improvement...

**Comment by ashb** [comment] 2017-04-20 15:28
Yes, that is correct. I'm not sure if it's required or just convention but the firstConsecutiveIp is typically 14? 16? IPs back from the end of that subnet, so 10.10.223.239 in your case. and yes I will work on a PR to improve the docs around the custom IP stuff.

**Comment by rocketraman** [comment] 2017-04-20 16:36
@ashb The configuration above worked perfectly. One interesting behavior: this time, the DNS and Dashboard pods stayed in "Pending" state, without any crash loop. As soon as I applied the custom VNET workaround step #7 documented @ https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.md all the pods transitioned quickly to Running state.

**Comment by rocketraman** [comment] 2017-04-20 16:45
@ashb One other thing that is probably useful to document as well : Docker tries to find an unused range in 172.16.0.0/12 for its internal networking (I'm not sure of the details here). So one should be careful when configuring Kubernetes to use that range -- probably best to avoid it completely.

**Comment by jackwoodward** [comment] 2017-04-21 00:18
@rocketraman am I correct in assuming that the workaround step 7 documented is not needed if you did not deploy to a custom template? I don't see any system pods pending and see no errors in their logs either but my pods aren't resolving names.

Windows IP Configuration

   Host Name . . . . . . . . . . . . : xxxxxxx
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : xxxxxx.dx.internal.cloudapp.net

Ethernet adapter vEthernet (Container NIC 301e84e9):

   Connection-specific DNS Suffix  . : xxxxxx.dx.internal.cloudapp.net
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
   Physical Address. . . . . . . . . : xx-xx-xx-xx-xx-xx
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::dc09:9db1:bb71:31a4%33(Preferred)
   IPv4 Address. . . . . . . . . . . : 172.22.149.138(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . : 172.22.144.1
   DNS Servers . . . . . . . . . . . : 172.22.144.1
                                       10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter vEthernet (Container NIC 5ed028c7):

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #6
   Physical Address. . . . . . . . . : 00-15-5D-B4-01-1E
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::bdf9:86d8:31a8:1cbe%37(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.244.1.37(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :
   DNS Servers . . . . . . . . . . . : 10.0.0.10
   NetBIOS over Tcpip. . . . . . . . : Disabled

**Comment by rocketraman** [comment] 2017-04-21 01:00
> @rocketraman am I correct in assuming that the workaround step 7 documented is not needed if you did not deploy to a custom template?

You said "custom template" -- did you mean "custom VNET"? I believe the workaround step 7 is only needed if you deployed with a custom VNET. Which in turn, seems to be necessary if you want to use @ashb 's changes to deploy with specific subnet ranges. Otherwise there is no place to specify the KubernetesSubnet addressPrefix within the kubernetes.json fed to acs-engine.

**Comment by jackwoodward** [comment] 2017-04-21 01:31
Yes sorry I meant vnet. Wasn't trying to deploy to a specific subnet range so sounds like I don't need the work around. Too bad because that means I need to find another reason dns is broken.

**Comment by rocketraman** [comment] 2017-04-21 02:11
> Yes sorry I meant vnet. Wasn't trying to deploy to a specific subnet range so sounds like I don't need the work around. Too bad because that means I need to find another reason dns is broken.

Well, its interesting... I had DNS resolution problems on the cluster I set up earlier today too. Since resolution was intermittent, I realized one of the DNS pods had failed to start or crashed or something... and indeed restarting it from the dashboard worked. Perhaps you are having a similar issue?

**Comment by jackwoodward** [comment] 2017-04-21 02:38
Reset the all the pods but that didn't fix the issue and the issue seems to be that the dns server address is wrong. Neither of the dns pods are listed for my pod, I manually set the dns to the dns pods and now things are working, now why  are the dns address wrong.

**Comment by jackwoodward** [comment] 2017-04-21 05:02
So the issue turned out to be that kubeproxy had some errors when starting up. Restarting the service fixed the dns issue. Still have a weird 2-3 minute delay before I can talk to the internet when a container comes up but that is so far as I can tell "normal". Attached the log from kubeproxy.
[kubeproxy.err-20170421T023511.653.txt](https://github.com/Azure/acs-engine/files/946056/kubeproxy.err-20170421T023511.653.txt)

**Comment by rocketraman** [comment] 2017-04-21 17:58
@ashb Looks like I spoke to soon about the deployment working and my DNS issues being resolved. All of Kubernetes is up and running, and all kube-system nodes and pods are in Running state. The logs of the DNS pods all seem fine.

However, as I am trying to deploy other containers, I see that they *intermittently* have DNS resolution problems. It seems to be an issue reaching the DNS server itself as opposed to the DNS server failing to resolve:

```
root@shell-437565471-6v8sp:/# cat /etc/resolv.conf 
search canary.svc.cluster.local svc.cluster.local cluster.local vgattl2qjeeuhjvrqqfthkxkze.vx.internal.cloudapp.net
nameserver 10.10.128.10
options ndots:5

root@shell-437565471-6v8sp:/# dig -t a www.google.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> -t a www.google.com
;; global options: +cmd
;; connection timed out; no servers could be reached
```

Some containers are able to talk to DNS, and others are not. Restarting a given container sometimes results in DNS working, and other times it remains broken. I tried rebuilding the cluster from scratch, and have the same result.

It really seems to be something related to the serviceCidr. I'm going to try rebuilding the cluster but leave the serviceCidr at the default value.

**Comment by jackwoodward** [comment] 2017-04-21 21:01
@rocketraman @ashb my cluster is using the default serviceCidr and is exhibiting the same behavior that @rocketraman is describing,

**Comment by rocketraman** [comment] 2017-04-27 06:02
@ashb  I believe the problem I was having with DNS resolution is described in issue #539 and resolved by pull #540. So I suspect the CIDR changes were not at fault at all. Unfortunately, it looks like the CIDR branch needs to be rebased to merge cleanly into the latest engine code.

**Comment by rocketraman** [comment] 2017-04-27 21:41
FYI I had no problems with the latest master + following the instructions provided by @ashb in comment https://github.com/Azure/acs-engine/issues/493#issuecomment-295329977.

The pull request to revert the revert for the CIDR changes is here: #546 . @anhowe it would be great if you could test this and see if this issue can be replicated.

**Comment by anhowe** [comment] 2017-04-28 15:36
@rocketraman - please try using CNI plugin, with all defaults (no change of CIDR), and you will see the issue.

**Comment by rocketraman** [comment] 2017-04-28 15:59
@anhowe How do I use the CNI plugin? I was unable to find anything in the docs on this.

**Comment by ashb** [comment] 2017-04-28 16:40
@rocketraman  This snippet in apimodel.json should do it.

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "kubernetesConfig": {
        "networkPolicy": "azure"
      }
    }
  }
}
```

(In the right thread this time)

**Comment by anhowe** [comment] 2017-04-28 16:51
@rocketraman - The CNI plugin is owned by @ofiliz , and he can help you with CNI related questions.  In addition to @ashb's template, here's a link to CNI examples https://github.com/Azure/acs-engine/tree/master/examples/networkpolicy.

**Comment by ofiliz** [comment] 2017-05-13 02:53
@anhowe @ashb I've found and fixed the regression. It has nothing to do with Internet connectivity. The pod subnet being passed to master (/12) and the "ClusterCIDR" (/16) being passed to proxy are incompatible when CNI plugin is enabled.

How do you want to put the original change back in?

**Closed** 2017-05-19 18:18 UTC
Labels: orchestrator/k8s, priority/P0
