### ISSUE TITLE
Reason why node is marked as NotReady

### ISSUE THREAD

**Issue by rushabhnagda11** [Azure/acs-engine#863] opened 2017-06-24 12:10 UTC
**Is this a request for help?**:
Yes
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
Node is marked as NotReady and a cascading effect takes places on my k8s cluster

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Not sure

**Anything else we need to know**:
In /var/log/kern.log of my k8s master server, I can see that one node has been marked as NotReady.
Is there a reason logged somewhere as to why this was done? This is a recurring issue every few days.

**Comment by JackQuincy** [comment] 2017-06-26 18:25
Can you look up these log  on the agents that are marked not ready and see if there are any details in there that might be helpful? 
cat /var/log/azure/cluster-provision.log 
sudo journalctl -u kubelet

**Comment by rushabhnagda11** [comment] 2017-06-28 13:22
[Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.775805       1 controller_utils.go:285] Recording status change NodeNotReady event message for node k8s-agentpool1-18420427-2
Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.775935       1 controller_utils.go:203] Update ready status of pods on node [k8s-agentpool1-18420427-2]
Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.776570       1 event.go:217] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-agentpool1-18420427-2", UID:"6b8de3e3-04d8-11e7-9280-000d3af03aaf", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node k8s-agentpool1-18420427-2 status is now: NodeNotReady](url)

**Comment by rushabhnagda11** [comment] 2017-06-28 13:24
This just happened. A node is almost at random marked as NotReady by my master. However, I was also unable to ssh into my node when it was marked as notready. Could a very high CPU process be running on the node at this time? I'm using only a 2 core machine.

I've had a look at the logs on the node around this time, and there was nothing useful there. Can you tell me how to proceed from here

> Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.775805       1 controller_utils.go:285] Recording status change NodeNotReady event message for node k8s-agentpool1-18420427-2
Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.775935       1 controller_utils.go:203] Update ready status of pods on node [k8s-agentpool1-18420427-2]
Jun 28 12:18:37 k8s-master-18420427-0 dockerd[22509]: I0628 12:18:37.776570       1 event.go:217] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"k8s-agentpool1-18420427-2", UID:"6b8de3e3-04d8-11e7-9280-000d3af03aaf", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node k8s-agentpool1-18420427-2 status is now: NodeNotReady

**Comment by DonMartin76** [comment] 2017-07-04 13:57
I am seeing exactly this behavior as well, and this morning we had it on a small production cluster, consisting of 3 agent DS12_v2 machines, where two machines were taken out with `NotReady` status almost simultaneously, taking down the third in the wake of that, due to too many containers being run on it simlutaneously (THAT was our fault, the other, we don't think so).

Looking at the `journalctl -u kubelet`, I see that at one point, the kubelet starts to take down containers, but I can't understand why:

```
Jul 04 07:37:40 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:40.506695    1772 server.go:740] GET /metrics: (83.688577ms) 200 [[Prometheus/1.7.1] 10.240.255.5:54372]
Jul 04 07:37:42 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:42.423130    1772 kubelet.go:1797] SyncLoop (DELETE, "api"): "aurora-mobile-green-1188259835-v9lrd_default(79f859fc-
Jul 04 07:37:42 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:42.423706    1772 docker_manager.go:1559] Killing container "0c2db2806017d231e7f2df23d477531d08fdae727904df6935f6780
Jul 04 07:37:42 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:42.487155    1772 kubelet.go:1797] SyncLoop (DELETE, "api"): "auth-redis-3305003549-cdz0p_default(8e25d914-6070-11e7
Jul 04 07:37:42 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:42.487681    1772 docker_manager.go:1559] Killing container "83d5e69f08d1dc7502d4f4cbee29e566924c816a3482312234c9d5c
Jul 04 07:37:42 k8s-agentpool1-22420894-1 docker[1528]: I0704 07:37:42.547828    1772 kubelet.go:1797] SyncLoop (DELETE, "api"): "auth-server-1912670786-4p2gx_default(55062242-608a-11e
J
(this goes on for quite a while)
```

It also `DELETE`s e.g. `kube-dns` and `heapster`, for no reason I can see.

I still have the logs for the machines, where should I look, what could I look for?

**Comment by DonMartin76** [comment] 2017-07-05 06:50
It may be related to #906, and that the `kubelet` thinks it has to evict pods for not responding. How could I see that? We increased the size of our NFS server to a DS3, and since then it hasn't occurred.

**Comment by rushabhnagda11** [comment] 2017-07-05 10:51
I can confirm this issue. It happens twice a day on a single machine, and my disk read graphs are through the roof. Still trying to figure what process is doing this.

**Comment by bogdangrigg** [comment] 2017-07-05 13:24
@DonMartin76 We've had a similar issue yesterday.
For us it seemed to be related to an Azure networking issue ([Intermittent connection failures in VPN Gateway](https://azure.microsoft.com/en-us/status/history/))

@JackQuincy Is there a way to externally monitor the reasons why a node is marked as NotReady?

**Comment by JackQuincy** [comment] 2017-07-05 18:02
@colemickens @brendandburns  Is there a way like @bogdangrigg is requesting?

**Comment by theobolo** [comment] 2017-10-19 22:33
To add a case to that problem, i'm using ACS with K8S 1.7.5 and since 9 P.M, all my nodes are running randomly down, kubelet is stopping posting node status one after another. 

Surprisingly, it happend on my three different clusters at the same time, take a look at my grafana monitoring status on the 3 different clusters : 

1 - 
![image](https://user-images.githubusercontent.com/7281773/31797272-c04192e0-b52d-11e7-95da-83943c3ae4bc.png)

2 - 
![image](https://user-images.githubusercontent.com/7281773/31797278-c73900f6-b52d-11e7-8b4c-966f43b474fe.png)

3 - 
![image](https://user-images.githubusercontent.com/7281773/31797284-cdcb5f0e-b52d-11e7-9e88-05a36a624b1e.png)

Is that linked to a possible Azure API connection problem ? Kubelet is stopping positing status because Azure API is unreachable for a while ? 

Since the problem started at the same time on 3 different clusters it must be linked to something external to Kubernetes. 

My clusters are not OOMed ou CPU overloaded : 

![image](https://user-images.githubusercontent.com/7281773/31797382-52396a1a-b52e-11e7-84fc-5f65b4b8ef26.png)

See : https://github.com/kubernetes/kubernetes/issues/43516

**Comment by DonMartin76** [comment] 2017-10-20 06:49
We are also facing similar issues since this morning on our production cluster. Fortunately, not all nodes go down at the same time (this time), but rather one after the other, so that the application is still stable.

![bildschirmfoto 2017-10-20 um 08 47 26](https://user-images.githubusercontent.com/7326883/31808432-62113752-b573-11e7-9c64-83f0550d7da0.png)

Which logs would make sense to look into to find a possible cause for this behavior? `kubectl get events` does not render anything useful (just states the obvious).

**Comment by DonMartin76** [comment] 2017-10-20 10:08
This behavior is continuing for the entire day right now; we will reprovision the cluster with `acs-engine` 0.8.0 this afternoon and see whether that helps. The cluster showing this behavior was created with acs-engine v0.5.0 for Kubernetes 1.7.2 three days ago.

**Comment by theobolo** [comment] 2017-10-20 10:16
@DonMartin76 I really don't want to use the "reprovision" solution since i deployed all my clusters just 1 week ago and since i've a full Production and criticals applications running right now ... Let me know about your tests Don should be great. :D

**Comment by DonMartin76** [comment] 2017-10-20 10:47
@theobolo Will let you know how it works out. We reprovision production every week with zero downtime deployments anyway, so it is not a huge issue to do it one time out of the ordinary for us.

Which region are you in? We are in North Europe.

**Comment by theobolo** [comment] 2017-10-20 11:24
Oh really every week ! Did you automate all the migration process ? like migrate Data Disks provisionned on Azure, DNS rules, ingress ? Because i've a lot of critical applications Kafka, Mongo etc etc. I'm able to migrate with 0 downtime too but i'm taking 1/2 day to do it on my Three clusters. 

Because the only point where i'm struggling is migrate my managed Disks i opened an issue to ask if it's possible to mount a specific Managed Disk on a pod or a Deployment : https://github.com/Azure/acs-engine/issues/1484

**Comment by DonMartin76** [comment] 2017-10-20 11:44
We halt some processing for the time of the provisioning, which does not affect the customer; and customer data is kept on Cosmos, which we can just use from both the "old" and "new" cluster. 

We clone data disks to a backup resource group first, then clone them back into the new resource group, in short. Fully scripted. We don't use mounts of managed disks to Pods, but implement an NFS server which has them mounted to take the state out of the cluster completely (but we reprovision that thing as well).

Works for us, but YMMV.

Nodes are still flaky on the current production cluster FWIW, and I have encountered some breaking changes going from 0.5.0 to 0.8.0 (Master nodes are tainted instead of cordoned, breaking our DaemonSets).

**Comment by DonMartin76** [comment] 2017-10-20 15:33
**Update**: After an update to acs-engine 0.8.0, and Kubernetes 1.7.7, the problem **still** occurs.

```
2017-10-20 17:26:23 +0200 CEST   2017-10-20 16:02:53 +0200 CEST   10        k8s-agent-33434527-0                   Node                                                   Normal    NodeNotReady              controllermanager                 Node k8s-agent-33434527-0 status is now: NodeNotReady
```

Similar error messages cycle through for the other nodes as well, and there seem to be no apparent reasons. The nodes are available via `ssh` when remoting into them via the master as a jump host, and do not seem to lose the container workload either, except if the nodes aren't reachable for more than 5 minutes - which triggers an eviction by the master and they are rescheduled somewhere else.

I have no clue where to dig here.

**Comment by DonMartin76** [comment] 2017-10-21 06:59
I think this _may_ be the same as this issue: #220 - @theobolo Can you check your `kube-controller-manager` container logs (in the `kube-system` namespace) for `FullDisruption` messages? I have tons of those in my logs.

**Comment by theobolo** [comment] 2017-10-21 10:24
Hey @DonMartin76 my clusters are back to a normal state since 5 A.M this morning, no more NotReady > Ready switches. 

Look at the Grafana kubelet metrics : 

PRODUCTION : 
![image](https://user-images.githubusercontent.com/7281773/31850828-0f9ed438-b65a-11e7-876d-70c63d2767d2.png)

STAGING : 
![image](https://user-images.githubusercontent.com/7281773/31850836-2c47538a-b65a-11e7-8eb3-27a331d7a12d.png)

Should confirms that was an Azure problem ... I'll take a look at my kube-controller-manager logs to confirm your toughts. 

BTW thanks for having described your migration process, i should take a look to add a NFS layer for my apps.

**Comment by DonMartin76** [comment] 2017-10-23 07:52
Same here, problems just ceased Saturday morning at around 0230 GMT. I opened a support ticket to try to find the root cause on this one; I will return with more information if they find something useful.

**Comment by theobolo** [comment] 2017-10-23 08:05
@DonMartin76 Same here, opened an Azure issue to find what was wrong ... 👍

**Comment by DonMartin76** [comment] 2017-10-23 08:23
@theobolo Would you mind sharing the Azure region(s) your cluster(s) run on? Also North Europe, or somewhere else?

**Comment by theobolo** [comment] 2017-10-23 08:25
@DonMartin76 Also North Europe...

**Comment by theobolo** [comment] 2017-10-23 09:15
@DonMartin76 Not sure if you can see it : https://app.azure.com/h/RHDP-V40/377c3f but the bug is probably related to this...

**Comment by DonMartin76** [comment] 2017-10-23 09:36
@theobolo Thanks for the link, and yes, I can see it. Let's see whether my support issue renders the same result, they are currently investigating. It's interesting though that the same issue was reported on a non-acs-engine provisioned cluster as well (CoreOS with k8s 1.6.4), but also in the North Europe region. Happy they are really looking into it.

**Comment by malachma** [comment] 2017-10-25 12:47
Hello @theobolo  I currently work on the SR DonMartin76 had opended with us. Is it possible that you share the SR number with me so I can link both SRs together and can use your information as well to get more details about this beahviour.

Thanks in advance

**Comment by theobolo** [comment] 2017-10-26 13:17
@malachma Hello, my SR number is `117102316535791`.

We talked on slack, so you will maybe don't find anything intresting on the email feed. Btw the support team told me to wait until `RHDP-V40` issue resolution, that's the only explanation we found about that bug.

**Comment by kahoona77** [comment] 2017-10-27 08:37
Hi,
We are experiencing the same thing with our cluster, with three master nodes and 7 worker-nodes. Randomly some nodes go into "Not Ready" (master and worker nodes).
The issues started about the 19. of October and are still ongoing.

And I still haven't found a reason why. Do you have any hints where I could look?

We are in West Europe.

**Comment by theobolo** [comment] 2017-11-02 11:52
Any update on this ?

**Comment by smoerboegen** [comment] 2017-11-03 07:19
We had the same issue a couple of days ago. Opened a case with Azure support but no updates at all.

**Comment by ekarlso** [comment] 2017-12-08 09:48
Same problem here too.

**Comment by philipedwards** [comment] 2017-12-11 08:59
We experienced a major outage with multiple nodes going NotReady at 0900 ACST on Friday December 8. We're being forced to look at abandoning our ACS cluster as it bought our production infrastructure to its knees.

**Comment by smoerboegen** [comment] 2017-12-11 09:13
@philipedwards May I ask which version of k8s you are running? We are having the same problems running k8s 1.6.6.

**Comment by philipedwards** [comment] 2017-12-11 10:06
@smoerboegen We're on 1.5.3. Seeing that you're having similar issues on 1.6.6 and others on 1.7.5 eliminated upgrading K8s as a potential path forward.

**Comment by smoerboegen** [comment] 2017-12-20 07:11
The same problems also exists in AKS (managed kubernetes) with kubernetes 1.7.

**Comment by kahoona77** [comment] 2017-12-20 07:38
Hi,

we recreated our cluster with ACS-Engine and kubernetes 1.8.2 on November 7th. And since then we had not experienced the problem. I do not know if that anything to do with it, but it is running smooth since then.

**Comment by DonMartin76** [comment] 2017-12-20 09:00
We have had some sporadic issues which always recovered by themselves within an hour approximately. It has become a lot better, for unknown reasons. Since two weeks no issues now.

**Comment by philipedwards** [comment] 2017-12-20 22:21
We suffered another node NotReady issue on December 18th. This time it was a single node failure. The following log is in UTC and I've removed the noise.

> Dec 17 18:04:44 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:04:44.796491 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError _ssl.c:629: The handshake operation timed out
>Dec 17 18:13:33 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:13:33.901586 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
>Dec 17 18:26:03 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:26:03.905866 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP GET IOError The read operation timed out
>Dec 17 18:36:40 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:36:40.029952 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError The read operation timed out
>Dec 17 18:43:35 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:43:35.665494 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
>Dec 17 18:53:43 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 18:53:43.489388 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError The read operation timed out
>Dec 17 18:55:34 k8s-agent-HOSTNAME-4 docker[39292]: E1217 18:55:34.829591   39321 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: instance not found
>Dec 17 19:02:40 k8s-agent-HOSTNAME-4 docker[39292]: E1217 19:02:40.792426   39321 kubelet_node_status.go:302] Error updating node status, will retry: Operation cannot be fulfilled on nodes "k8s-agent-b3e1e1aa-4": the object has been modified; please apply your changes to the latest version and try again
>Dec 17 19:02:40 k8s-agent-HOSTNAME-4 docker[39292]: I1217 19:02:40.885446   39321 kubelet_node_status.go:358] Recording NodeHasSufficientDisk event message for node k8s-agent-b3e1e1aa-4
>Dec 17 19:02:40 k8s-agent-HOSTNAME-4 docker[39292]: I1217 19:02:40.885480   39321 kubelet_node_status.go:358] Recording NodeReady event message for node k8s-agent-b3e1e1aa-4
>Dec 17 19:13:37 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 19:13:37.441429 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
>Dec 17 19:27:06 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 19:27:06.787978 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError The read operation timed out
>Dec 17 19:43:40 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 19:43:40.148011 INFO Event: name=WALinuxAgent, op=HeartBeat, message=, duration=0
>Dec 17 19:56:50 k8s-agent-HOSTNAME-4 python3[1186]: 2017/12/17 19:56:50.608422 INFO [HTTP Retry] Attempt 2 of 3: [HTTP Failed] HTTP PUT IOError The read operation timed out

Does any of this leap out at anyone?

**Comment by brendandburns** [comment] 2017-12-20 22:25
I'm seeing this:

Dec 17 18:55:34 k8s-agent-HOSTNAME-4 docker[39292]: E1217 18:55:34.829591 39321 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: instance not found

Which I think means that the node was deleted?

Is that true?

--brendan



________________________________________

**Comment by philipedwards** [comment] 2017-12-20 22:29
The node was not deleted from our end, the incident was at 5:30am and no one was working at that time. 

Do you suspect that log entry means it was deleted from the Azure side or deleted from the k8s cluster?

**Comment by philipedwards** [comment] 2017-12-20 22:33
I also back to the logs from our previous incident where we lost 3 out of 4 nodes. 

k8s-agent-B3E1E1AA-1 was the only node to survive the incident, the other entry is from our master node

>Dec  7 22:26:49 k8s-agent-B3E1E1AA-1 docker[23202]: E1207 22:26:49.770011   23237 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: instance not found
>Dec  7 22:26:49 k8s-master-B3E1E1AA-0 docker[1806]: E1207 22:26:49.770756    1874 kubelet_node_status.go:302] Error updating node status, will retry: failed to get node address from cloud provider: instance not found

**Comment by brendandburns** [comment] 2017-12-20 22:50
Deleted on the Azure side.

Can you send me the subscription/resource id of a VM that corresponds to k8s-master-B3E1E1AA-0

I'd like to cross-check with the ARM logs.

Thanks
--brendan



________________________________________

**Comment by brendandburns** [comment] 2017-12-20 22:59
Ah, I took a deeper look at the code, I think I see the bug...



________________________________________

**Comment by brendandburns** [comment] 2017-12-20 22:59
(it would still be useful to get the resource id...)



________________________________________

**Comment by philipedwards** [comment] 2017-12-20 23:18
@brendandburns email sent.

**Comment by brendandburns** [comment] 2017-12-20 23:45
Bug fix is here:

https://github.com/kubernetes/kubernetes/pull/57484

Once that's merged we'll pick back to at least 1.8.x

--brendan



________________________________________

**Comment by philipedwards** [comment] 2017-12-21 00:40
@brandandburns - were you able to find anything in the logs relating to our last outage? Is it possible to go back to the previous incident and confirm it was the same issue?

I would like to add this detail to our incident reports.

**Comment by DonMartin76** [comment] 2017-12-21 15:46
@brendanburns So, in short, this may be due to an unresponsive Azure API, or API calls to Azure which do not reply the way which is expected? Is it likely that this happens a lot so that it can cause these kinds of outages?

We had periods of 24h+ where this happened on and off. Now this hasn't happened for a while, and the periods are usually shorter than an hour, and the scheduler usually doesn't start to reschedule things just yet.

**Comment by brendandburns** [comment] 2017-12-21 16:19
I don't know exactly what errors would cause the sdk to not return a autorest.DetailedError, but at the very least I would suspect that something in the transport layer (eg http timeout) would return a different error.

I'll follow up with the sdk team to better understand the conditions that would trigger this and follow up on this thread.

But nonetheless, we're pushing to get this cherry picked ASAP so that people can update to a fixed binary.

--brendan

________________________________

**Comment by DonMartin76** [comment] 2017-12-21 19:24
Happy to hear this. We have been chasing for the cause of these things for over a month now (MS support in Munich and I), and until now we haven't been able to really pin it down. We had it down to something between Kubernetes and the Azure API, but couldn't reproduce, and thus it's difficult to get a real diagnosis on it. REALLY appreciate you pitching in on this, Brendan.

**Comment by colemickens** [comment] 2017-12-21 19:26
I'd like to understand this better, if possible. The bugfix makes sense (sorry, that'd be my bug), but I don't yet understand how it manifests itself as "Node NotReady" (though I'd agree it seems too coincidental to not be related).

It looks like the errors above are coming from kubelet failing to get its own node status to self report IPs. I would have assumed that only KCM would actually handle "instance not found" and consider it deletion of a node.

If `kubelet` were handling `instance not found` and treating it as a deletion, then I would've expected to see the Node object disappear entirely, and would have expected to see errors for kubelet trying to PUT it's node status for a node object that no longer exists.

Additionally, if this is enough to cause things to get "stuck", I'm not sure I understand how things are recovering without the `kubelet` being restarted such that it tries to do an initial POST to create its own node object.

**Comment by brendanburns** [comment] 2017-12-21 19:31
What I believe is happening is this:
   In order to post status, kubelet needs it's IP address
   Lookup of the node fails due to some transient reason, kubelet sees "not
found" and the entire node status update to master is aborted.
   Do this enough times in a row, and the node transitions into NotReady
state.
   If eventually, the transient error fixes itself, and the node starts
posting status again, node goes back to Ready state.
   If on the other hand, the issue goes on long enough, the NodeController
on the master is going to delete the Node, which will require a Kubelet
restart (though that's a bug imho) to recover from.

   Switching to IMDS will also fix this in general, since kubelet won't
need an API call to get it's IP address.

**Comment by snebel29** [comment] 2018-01-02 10:16
I think we're suffering from this issue as well, every 2 weeks approx. recovering on its own and together some networking interface ready not ready errors in the logs, I could provide further details if required.

Thanks

**Comment by malachma** [comment] 2018-01-02 12:07
@snebel The only workaround I'm aware off to get a more reliable IP detection , till the merge is available in the k8s version we ship with ACS or AKS, is to enable the MetadataService.
To do this alter the  /etc/kubernetes/azure.json
Change the flag from : "useInstanceMetadata": false
 to : "useInstanceMetadata": true
And restart the kublet instance. Perform this modification on all of your agents.

**Comment by snebel29** [comment] 2018-01-02 12:55
Hi @malachma,
First all thanks for the hint, it's really appreciated!

I don't see that flag set into the `azure.json` file "It just doesn't exist", I guess the default is true? since this command

```
curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-04-02"
```
Seems to return back good instance metadata results, or I'm missing something?

**Comment by malachma** [comment] 2018-01-02 13:53
@snebel29  That is interesting that you don't see the flag as mentioned. Adding this  flag to this config-file and set it to true should help in this case. By default the metadata services is not used if take 1.8 as reference. What is your k8s version by the way?

**Comment by snebel29** [comment] 2018-01-02 14:41
Hi,
My k8s version is 

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.1", GitCommit:"1dc5c66f5dd61da08412a74221ecc79208c2165b", GitTreeState:"clean", BuildDate:"2017-07-14T02:00:46Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```
and the `acs-engine` version used to create the cluster was

```
commit 24a478e20260850ef610b4297b077b3eb21638e9
Author: Adam Greene <adam.greene@gmail.com>
Date:   Wed Jul 5 16:48:46 2017 -0700

    update kubernetes doc (#860)
```

Thanks

**Comment by brendanburns** [comment] 2018-01-03 19:38
I don't think 1.6.6 supports IMDS... Any chance you can upgrade?

--brendan

**Comment by snebel29** [comment] 2018-01-04 08:47
Hi @brendanburns ,
While not funny if that will solve/workaround the issue I'm willing to... is there a reasonable level of certainty with that workaround? Is there any further information on the fix?

Thanks in advance

**Comment by brendandburns** [comment] 2018-01-04 16:19
IMDS will definitely make things better. The correct fix is being cherry picked into the 1.7, 1.8 and 1.9 release branches.

So I think you have two choices:

Upgrade now to get IMDS support.

Wait for the cherry pick release with the correct fix (1-2 weeks) and upgrade then to the complete fix.

Sadly 1.6.x is nearly a year old and outside of the window for patching at this point.

--brendan

________________________________

**Comment by snebel29** [comment] 2018-01-04 16:32
Hi @brendanburns,
I really appreciate that information, that will allow us to plan accordingly to our internal roadmap of changes, I think this will probably be worth for us to move to the last stable release and might try the workaround in the meanwhile if that upgrade gets internally delayed.

Thanks!

**Comment by jamoham** [comment] 2018-01-30 02:36
I hit this same problem on 1.7.9 version:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommit:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.9", GitCommit:"19fe91923d584c30bd6db5c5a21e9f0d5f742de8", GitTreeState:"clean", BuildDate:"2017-10-19T16:55:06Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}


$ kubectl get nodes
NAME                        STATUS     AGE       VERSION
k8s-agentpool1-14934812-0   Ready      6d        v1.7.9
k8s-agentpool1-14934812-1   NotReady   6d        v1.7.9
k8s-agentpool1-14934812-2   Ready      6d        v1.7.9
k8s-master-14934812-0       Ready      6d        v1.7.9
```

When will the fix be cherry picked into 1.7.x versions?

**Comment by nealabh** [comment] 2018-02-12 07:13
Still facing the same issue with 1.7.7, can you suggest how to upgrade on Azure Container Service.

**Comment by brendandburns** [comment] 2018-02-12 16:20
ACS engine has instructions on how to upgrade here:

https://github.com/Azure/acs-engine/blob/master/examples/k8s-upgrade/README.md

--brendan

________________________________

**Comment by mboersma** [comment] 2019-01-10 18:45
I'm closing this old issue since acs-engine is deprecated in favor of [aks-engine](https://github.com/Azure/aks-engine).

**Closed by mboersma** 2019-01-10 18:45 UTC
Labels: kind/bug, orchestrator/k8s, priority/P1
