### ISSUE TITLE
Changing node when mounting an Azure disk is taking forever

### ISSUE THREAD

**Issue by AlexGrs** [Azure/acs-engine#192] opened 2017-01-18 17:34 UTC
I have a pod with a persistent volume claim attached to it. After a first initialization, I tried to delete the pod to check how the system was going to behave.

The pod was indeed rescheduled on an other node. But I had to wait 15 to 20 minutes before my pod is finally up. 

During this period, I had multiple errors like:

```
Unable to mount volumes for pod "postgresql-43555_default(15fbe5fc-dda3-11e6-988d-000d3a319caa)": timeout expired waiting for volumes to attach/mount for pod "default"/"postgresql-43555". list of unattached/unmounted volumes=[azure]
Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "default"/"postgresql-43555". list of unattached/unmounted volumes=[azure]
```

```
E0118 17:31:27.938410    4494 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/azure-disk/kaaa4-dynamic-pvc-724196d3-dd9f-11e6-988d-000d3a319caa.vhd\"" failed. No retries permitted until 2017-01-18 17:33:27.938388518 +0000 UTC (durationBeforeRetry 2m0s). Error: Volume "kubernetes.io/azure-disk/kaaa4-dynamic-pvc-724196d3-dd9f-11e6-988d-000d3a319caa.vhd" (spec.Name: "pvc-724196d3-dd9f-11e6-988d-000d3a319caa") pod "15fbe5fc-dda3-11e6-988d-000d3a319caa" (UID: "15fbe5fc-dda3-11e6-988d-000d3a319caa") is not yet attached according to node status.
```

The disk is already formatted and is only 10Gi. I modified `hyperkube` to use lazy mkfs to format disk. Did i miss something ?

**Comment by colemickens** [comment] 2017-01-18 17:38
It can still hit a timeout edge case due to it giving up on the attach operation until a later retry but it shouldn't take 20 minutes, nno.

I was using builds over the weekend with the lazyinit patch and this patch (https://github.com/kubernetes/kubernetes/pull/38865) and a PVC and a dynamic volume was created and attached in less than 5 minutes.

**Comment by AlexGrs** [comment] 2017-01-18 17:48
Well it's quite strange. It seems I hit this issue quite regularly. 

I wanted to use this for our database, but if the database pod is reschedule on an other node, it means we will have 5 to 15 minutes of downtime each time it happens. Or it will need a failover.

Do you have any reco ?

**Comment by AlexGrs** [comment] 2017-01-18 21:10
You mentionned you used patch by @codablock ([kubernetes/kubernetes#38865](https://github.com/kubernetes/kubernetes/pull/38865)) but also the lazyinitpatch: are you talking about two different patch or are they the same ?

PS: Great they merged the pull request for mkfs.ext4 in master. Can't wait to have it in a release `1.5.3`

**Comment by colemickens** [comment] 2017-01-18 21:21
I was getting confused with this patch which is not yet merged: https://github.com/kubernetes/kubernetes/pull/40066

Please note, all three (including this one, also related to Azure disks: https://github.com/kubernetes/kubernetes/pull/40030) will need to be cherry-picked to ensure they're in 1.5.3.

**Comment by codablock** [comment] 2017-01-18 21:58
@AlexGrs There are still other issues which negatively affect attach/detach of disks, but it's hard to nail them down and figure out how to reproduce these. Do you see the delay of 20 minutes every time?

When this happens again, can you check which node the POD is rescheduled to and manually watch how long it takes till Azure Portal shows the disks being attached and detached? Also, can you check on the old and new node how long it takes till you see the disks disappearing and appearing under /dev/sd*?

**Comment by colemickens** [comment] 2017-01-18 22:45
A better source of truth is to look at resources.azure.com and then find the VM and look at the VM itself and compare against the instanceView. Usually in these "bad" cases, the VM model and the instance view diverge and is an indicator/source of the underlying problem...

Basically, more data is needed to develop a better heuristic and to give to the right folks in Azure to improve this scenario.

@jmspring for any thoughts in this area.

**Comment by jmspring** [comment] 2017-01-19 05:33
In talking with Kal today, he mentioned querying the specific state of the disk resource today in place of the instance view.  I have not looked at his approach closely, but trust him.

For me, on detach, the vm state and the instance view we're *required* to be sure.

It's possible checking the direct disk resource state is beneficial too.

-j

**Comment by codablock** [comment] 2017-01-19 08:52
At step 2, did you also observe the dmesg and /dev/sd* on agent-1? Did it appear at the same time?

**Comment by AlexGrs** [comment] 2017-01-19 09:03
I did it again, agent-1 to agent-0

It takes again 7 minutes to mount disk from one machine to the other (exactly the same time). As soon I see the signal in dmesg logs, the new disk is there in `/dev/sdc` 

**Agent-1: Unmount** 
```
[Jan19 08:54] cbr0: port 3(veth46a42da0) entered disabled state
[  +0.001066] device veth46a42da0 left promiscuous mode
[  +0.000002] cbr0: port 3(veth46a42da0) entered disabled state
```

**Agent-0: +7 minutes**
```
[Jan19 09:01] scsi 5:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 4
[  +0.009755] sd 5:0:0:1: Attached scsi generic sg4 type 0
[  +0.000113] sd 5:0:0:1: [sdd] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[  +0.000560] sd 5:0:0:1: [sdd] Write Protect is off
[  +0.000003] sd 5:0:0:1: [sdd] Mode Sense: 0f 00 10 00
[  +0.000164] sd 5:0:0:1: [sdd] Write cache: enabled, read cache: enabled, supports DPO and FUA
[  +0.176249] sd 5:0:0:1: [sdd] Attached SCSI disk
[  +0.488145] sd 5:0:0:1: [storvsc] Sense Key : Illegal Request [current]
[  +0.000004] sd 5:0:0:1: [storvsc] Add. Sense: Invalid command operation code
[  +0.000241] sd 5:0:0:1: [storvsc] Sense Key : Illegal Request [current]
[  +0.000002] sd 5:0:0:1: [storvsc] Add. Sense: Invalid command operation code
```

**Comment by codablock** [comment] 2017-01-19 15:40
@AlexGrs can you test with https://github.com/kubernetes/kubernetes/pull/40148?

**Comment by codablock** [comment] 2017-01-19 15:46
Ah, and in your last tests, was https://github.com/kubernetes/kubernetes/pull/40066 already included or not?

**Comment by AlexGrs** [comment] 2017-01-19 15:50
I will test as soon as #193 and #194 are fixed. I deleted mu last cluster and I can't manage to create a new one due to those issues.

**Comment by AlexGrs** [comment] 2017-01-23 14:31
I wanted to try @colemickens steps provided:

- clone kubernetes
- `export REGISTRY=docker.io/colemickens`
- `export VERSION=some-version`
- `./hack/dev-push-hyperkube.sh`

But for an unknown reason it failed:

```
Env for linux/amd64: GOOS=linux GOARCH=amd64 GOROOT=/usr/local/go CGO_ENABLED= CC=
go build k8s.io/kubernetes/cmd/hyperkube: /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
!!! Error in /go/src/k8s.io/kubernetes/hack/lib/golang.sh:562
  'go install "${goflags[@]:+${goflags[@]}}" -gcflags "${gogcflags}" -ldflags "${goldflags}" "${nonstatics[@]:+${nonstatics[@]}}"' exited with status 1
```

**Comment by colemickens** [comment] 2017-01-23 20:09
Please file a separate issue on the kubernetes repo for that issue. (But it looks like it's something on your system if `link` is being killed. Do you have sufficient ram, etc?)

**Comment by colemickens** [comment] 2017-02-03 20:13
I'm closing this as the issue has gone off topic and disk issues in kubernetes should probably be tracked in https://github.com/kubernetes/kubernetes anyway.

**Closed** 2017-02-03 20:13 UTC
Labels: enhancement, orchestrator:k8s, priority/P1
