### ISSUE TITLE
0.13.0 masters don't survive reboot

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2282] opened 2018-02-15 10:47 UTC
**Is this a request for help?**: sure, as I can't solve the problem by myself

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): issue

---

**What version of acs-engine?**:
0.13.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
K8s server 1.8.6, 1.8.8

**What happened**:
When bootstrapping a fresh cluster (master and agent scale seem to not matter in this case) on **AzureGermanCloud**, k8s masters do not recover after `sudo reboot` and stay `NotReady`. In addition, there is a temporary network outage, meaning that a publicly available service (i.e. nginx) running on an agent, is temporarily not reachable (I guess at the moment the rebooting master tries to come back). 
I see on the failing master:
```
$ sudo service kubelet status
Feb 15 10:20:46 k8s-master-33131957-2 docker[1794]: E0215 10:20:46.487462    1867 kubelet.go:2095] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: ...

```
**When using acs-engine `0.12.0`, this whole issue does not happen.**
The difference is here (scroll right):
```
0.13.0:
k8s-agentpool1-33131957-0   Ready     agent     29m        v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.13.1
k8s-master-33131957-0       Ready     master    28m        v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.13.1
k8s-master-33131957-1       Ready     master    29m        v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.13.1
k8s-master-33131957-2       NotReady  master    29m        v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.11.0-1016-azure   docker://1.13.1

vs. 0.12.0:
k8s-agentpool1-33131957-0   Ready     agent     16m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.4.0-59-generic   docker://1.12.6
k8s-master-33131957-0       Ready     master    16m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.4.0-59-generic   docker://1.12.6
k8s-master-33131957-1       Ready     master    16m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.4.0-59-generic   docker://1.12.6
k8s-master-33131957-2       Ready     master    16m       v1.8.6    <none>        Debian GNU/Linux 8 (jessie)   4.4.0-59-generic   docker://1.12.6

```
Version `0.12.0` deploys Ubuntu 16.04.1 with some *standard* kernel, version `0.13.0` deploys Ubuntu 16.04.3 with azure specific kernel. (Why does kubectl report Debian 8?). I've tried using `Standard_D..` machine types instead of `Standard_A2_v2`as it was proudly announced in ReleaseNotes, but no luck with them, too.

I wonder if anyone ever tested rebooting a master. Maybe that could also be a cloud specific problem

When you tell me, what exact configuration you want to see, I could provide logs.

**What you expected to happen**:
masters survive reboot

**How to reproduce it** (as minimally and precisely as possible):
https://gist.github.com/ITler/3a006c3755f14282e0aff2c7149351df

**Anything else we need to know**:
I don't use CNI but KubeRoute(?) `"networkPolicy": "none"`

**Comment by ITler** [comment] 2018-02-15 13:33
also for 1.9.3

**Comment by JunSun17** [comment] 2018-02-20 08:32
Checked v0.12.0 kubelet log and it also contains the container network error, so not sure it is the root cause.

Check the api server log and after reboot of v0.13.0 deployment, there are lots of timeout error and it looks the api server is kept restarting, more specifically, an error says:

{"log":" [[hyperkube/v1.8.6 (linux/amd64) kubernetes/6260bb0] 127.0.0.1:39784]\n","stream":"stderr","time":"2018-02-20T08:25:56.106965717Z"}
{"log":"E0220 08:25:56.107404       1 client_ca_hook.go:78] Timeout: request did not complete within allowed duration\n","stream":"stderr","time":"2018-02-20T08:25:56.107546444Z"}
{"log":"F0220 08:25:56.107478       1 hooks.go:133] PostStartHook \"ca-registration\" failed: unable to initialize client CA configmap: timed out waiting for the condition\n","stream":"stderr","time":"2018-02-20T08:25:56.107556645Z"}

**Comment by CecileRobertMichon** [comment] 2018-02-20 21:25
Workaround is to run `sudo systemctl restart etcd` on the master that was rebooted. After that the node should go to ready. Looking into root cause and fix for this.

**Comment by fbuser1** [comment] 2018-02-22 09:04
+1

**Comment by imranq2** [comment] 2018-02-22 09:12
+1

**Comment by yuedai** [comment] 2018-02-23 05:24
+1

**Closed** 2018-02-23 20:38 UTC
Labels: in progress, kind/bug, orchestrator/k8s
