### ISSUE TITLE
Implement TLS bootstrapping for Kubernetes Nodes

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1065] opened 2017-07-20 21:02 UTC
**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Feature

**What version of acs-engine?**:
---
All

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:
Move Kubernetes nodes to use TLS bootstrapping for so that they have an individual identity.

https://kubernetes.io/docs/admin/kubelet-tls-bootstrapping

**Comment by lachie83** [comment] 2017-07-20 21:02
If we think this is something worth pursuing I'm willing to do the work.

**Comment by jackfrancis** [comment] 2017-11-06 21:39
duplicate of #956

**Closed by jackfrancis** 2017-11-06 21:39 UTC
Labels: duplicate
