### ISSUE TITLE
az deploy does not create container service

### ISSUE THREAD

**Issue by kaskavalci** [Azure/acs-engine#688] opened 2017-05-29 07:06 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**: `az group deployment create` does not create container service

**What you expected to happen**: `az acs list` should return container service. So I can use `az acs kubernetes get-credentials` to configure `kubectl`.

**How to reproduce it** (as minimally and precisely as possible): 

1. Follow kubernetes walkthrough.
2. Deploy cluster with 
```
$ az group deployment create \
    --name "<DEPLOYMENT NAME>" \
    --resource-group "<RESOURCE_GROUP_NAME>" \
    --template-file "./_output/<INSTANCE>/azuredeploy.json" \
    --parameters "@./_output/<INSTANCE>/azuredeploy.parameters.json"
```
3. Execute `az acs list`
4. It should return `[]`

**Anything else we need to know**: There is no information regarding creating kubectl config in Kubernetes walktrough. It may be good to add.

Also, I did not create service principal but used existing one.

**Comment by DonMartin76** [comment] 2017-05-29 12:16
I don't think `acs-engine` works like this, at least not currently. The `acs-engine` template actually doesn't create an ACS resource within the deployment, it just creates the VMs (Master(s) and Agents) and configures everything as a Kubernetes cluster.

The credentials (kubeconfig) you need is directly created as part of the template, one for each region to which you can deploy this.

You may see this as a disadvantage, but on the other hand, this also means you can use `acs-engine` to deploy Kubernetes clusters also to regions which does not have the ACS service.

Instead of doing a `az acs kubernetes get-credentials`, you simply use the `kubeconfig.<region>.json` from the `_output/kubeconfig` directory after your deployment is done.

Whether there are plans on also adding the ACS artifact (for whatever it's actually used) or not, I do not know, as I am not part of the product team.

/Martin

**Comment by kaskavalci** [comment] 2017-05-29 13:37
@DonMartin76 thanks for the input. I did not realize kubectl configs are already populated. I can access cluster with kubectl after using my region's config file.

However, documentation lacks this information and it is not clear how to use kubectl after the installation. I believe `az acs kubernetes get-credentials` should also work, to be consistent with portal insallation.

**Comment by DonMartin76** [comment] 2017-05-29 14:01
You have two (and a half) options to use the config with `kubectl`:

```
$ kubectl --kubeconfig=/path/to/kubeconfig.<region>.json get pods
...
$ export KUBECONFIG=/path/to/kubeconfig.<region>.json
$ kubectl get pods
...
$ cp /path/to/kubeconfig.<region>.json ~/.kube/config # this is the half option, don't do this
$ kubectl get pods
```

**Comment by amanohar** [comment] 2017-06-01 01:42
@kaskavalci `az acs kubernetes get-credentials ` will not work with a cluster created by ACS Engine (by design) because az group deploy does not call ACS RP to create a Kubernetes cluster.

**Comment by JackQuincy** [comment] 2017-06-08 21:57
closing this as it is by design. Using acs-engine to deploy essentially means you cannot az acs cli interface

**Closed by JackQuincy** 2017-06-08 21:57 UTC
