### ISSUE TITLE
Large VMSS / Managed Disks / Application Gateway support

### ISSUE THREAD

**Issue by jcrowthe** [Azure/acs-engine#316] opened 2017-02-22 20:36 UTC
As per this announcement (https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-managed-disks-and-larger-scale-sets/) Virtual Machine Scale Sets now can have a max of 1000 nodes, when based on Managed Disks. In addition to this, after discussions with @rgardler and Mohan Vedula, it is clear that the Azure Load Balancer will not support a VMSS with more than 100 nodes, but instead the Azure Application Gateway must be used.

This is a request for ACS-engine to support 1000-node VMSS, based on Managed Disks with Application Gateway support. Let's discuss!

**Comment by colemickens** [comment] 2017-02-22 20:39
I guess this should work now, other than the fact that we pre-deploy an L4 Load Balancer for the DC/OS and Swarm clusters...

We would need to discuss this. There are distinct disadvantages to using AppGateway and thus this posses a potential maintenance burden if we have to support L4 and L7 balancers in perpetuity.

Anyway, if you're interested in this, I'd recommend removing the load balancer from the template, bump the agent count up to 400 or something and try it out and see what happens.

**Comment by jcrowthe** [comment] 2017-02-22 20:55
I assume I would need to use the managed disks flag as well. It seems like this is still using the preview API in the output template. Will this cause any problems, or is there an alternative API version I can write in?

`"apiVersionStorageManagedDisks": "2016-04-30-preview",`

Also, I would be interested to discuss here the distinct disadvantages of the AppGateway, as they may affect my clusters as well. Would you be willing to detail at least a few of these?

**Comment by colemickens** [comment] 2017-02-22 21:12
Good eye! The preview version was surprising to us, but that is the current apiversion that should be used, even though it is generally available. CC: @anhowe as we had an internal thread about this to see if we were going to get a stable, non-preview version soon.

As for AppGateway, most of this is second-hand, but confirmed by many people:
* slow to provision
* slow to reconfigure
* HTTP/HTTPS only, no TCP or UDP
* expensive

**Comment by anhowe** [comment] 2017-02-23 17:29
The header "2016-04-30-preview" is the GA version for managed disks and the latest VMSS feature.

One possibility to achieve this is that we allow 1000 nodes for "private" agent pools.  Then when you want to load balance, you just put the public ip and loadbalancer on the agent pool with <= 100 nodes.

**Comment by jcrowthe** [comment] 2017-03-06 17:27
@colemickens @anhowe Any further update as to when there will be App Gateway support? This is a critical issue for my team.

**Comment by anhowe** [comment] 2017-03-06 19:02
@jcrowthe - what is the scenario and are you using DC/OS or Swarm?  For example, why do you need a thousand node FE vs a FE LoadBalancePool <= 100 nodes proxying to 1000 private agents?

**Comment by jcrowthe** [comment] 2017-03-06 22:34
One of the issues is the lack of SSL termination in the layer 4 LB. With thousands of nodes in a cluster, we will need this feature of the App Gateway.

**Comment by colemickens** [comment] 2017-03-06 22:36
I'm still confused. Do you need L7, do you need more than 100 nodes, or both? If you just need L7 and SSL termination, you're still better off running `nginx-ingress-controller`.

**Comment by colemickens** [comment] 2017-03-06 22:39
Reading it again, it seems like you need both. For the reasons mentioned earlier, I don't think this is something we will be looking at anytime soon. We might consider a PR, but I worry that this change would introduce a non-trivial amount of complexity into the templates. Furthermore, I have no idea how this psuedo-availability-set is going to work with the cloudprovider code in Kubernetes.

**Comment by anhowe** [comment] 2017-03-08 20:21
Closing as there is a workaround for this right now, of LB to <=100 nodes and those proxy to the larger VMSS.

**Closed by anhowe** 2017-03-08 20:21 UTC
Labels: priority/P2
