### ISSUE TITLE
Cannot create data disks with custom images

### ISSUE THREAD

**Issue by kosta709** [Azure/acs-engine#3941] opened 2018-10-03 14:18 UTC
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
v0.22.2
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes

**What happened**:
running acs-engine v0.22.2 with "diskSizesGB: [1023, 1023]" in cluster definition creates vm without datadisks
resulting azuredeploy.json does not contain "storageProfile": { "dataDisks": [ .... ] } section

it was working with acs-engine v0.19.5 

**What you expected to happen**:
acs-engine should deploy instances with datadisks 

**How to reproduce it** (as minimally and precisely as possible):
cluster-definition.json :
```
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.10",
        "kubernetesConfig": {
          "etcdDiskSizeGB": "32",
          "useManagedIdentity": true,
          "clusterSubnet": "10.245.0.0/16",
          "networkPlugin": "flannel",
          "apiServerConfig": {
            "--enable-admission-plugins":  "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,ExtendedResourceToleration"
          },
          "kubeletConfig": {
            "--enable-controller-attach-detach": "false"
          }         
        }
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "cluster-shared-2-ceph-1",
        "vmSize": "Standard_DS1_v2",
        "firstConsecutiveStaticIP": "10.239.254.5",
        "vnetCidr": "10.0.0.0/8",
        "vnetSubnetId": "/subscriptions/****/resourceGroups/cluster-shared-2-vnet/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet2",
        "imageReference": { "name": "ubuntu1804-041810-1", "resourceGroup": "general" },
        "preProvisionExtension": {
          "name": "configure-system",
          "singleOrAll": "All"
        }
      },
      "agentPoolProfiles": [      
        {
          "name": "ceph",
          "count": 3,
          "vmSize": "Standard_DS2_v2",
          "storageProfile": "ManagedDisks",          
          "availabilityProfile": "AvailabilitySet",
          "acceleratedNetworkingEnabled": true,
          "diskSizesGB": [1023, 1023],
          "customNodeLabels": {
            "node-type": "rook"
          },
          "vnetSubnetId": "/subscriptions/****/resourceGroups/cluster-shared-2-vnet/providers/Microsoft.Network/virtualNetworks/vnet1/subnets/subnet2",
          "imageReference": { "name": "ubuntu1804-041810-1", "resourceGroup": "general" },
          "preProvisionExtension": {
            "name": "configure-system",
            "singleOrAll": "All"
          }      
        }        
      ],
      "linuxProfile": {
        "adminUsername": "ubuntu",
        "ssh": {
            "publicKeys": [
                {
                  "keyData": "****"
                }
            ]
        }
      },
      "extensionProfiles": [
        {
            "name": "configure-system",
            "rootURL": "https://raw.githubusercontent.com/codefresh-io/terraform-helpers/master/",
            "version": "v1",
            "extensionParameters": "cluster-shared-2",
            "script": "configure-system.sh"
        }
      ]
    }
  }
```
`acs-engine generate --output-directory _clusters/cluster-shared-2 cluster-definition.json `

generated azuredeploy.json will not contain  "storageProfile": { "dataDisks": [ .... ] } section and so next `az group deployment create ... ` will create vms without datadisks (but complete sucessfully)
**Anything else we need to know**:
it was working with v0.19.5 
as a workaround I add "dataDisks" section to azuredeploy.json manually

I need new version (v0.22.2) of acs-engine because of fixes of scale issue https://github.com/Azure/acs-engine/issues/3697
but even with manual fixes in azuredeploy.json, running `acs-engine scale ... ` now adds vm without datadisks ...

**Comment by CecileRobertMichon** [comment] 2018-10-03 15:02
@kosta709 this is a regression introduced by adding the custom AKS distro. I will work on a fix, in the meantime you can specify `"distro": "ubuntu"` in your apimodel in the agent profile to opt out of the AKS distro and things will work as they used to.

**Comment by CecileRobertMichon** [comment] 2018-10-03 15:38
@kosta709 please disregard my previous comment, the AKS distro is not what is causing the issue. Still investigating to find root cause.

**Comment by kosta709** [comment] 2018-10-03 16:15
ok, thanks, waiting

**Comment by kosta709** [comment] 2018-10-03 17:43
Cecile, maybe it happens because of custom image i use?
acs-engine/parts/k8s/kubernetesagentresourcesvmas.t

        "storageProfile": {
          {{if not (UseAgentCustomImage .)}}
          {{GetDataDisks .}}
          {{end}}
previously i did not use custom image for this pool

**Comment by CecileRobertMichon** [comment] 2018-10-03 18:18
@kosta709 that's correct, I had missed that in your apimodel. This is by design I believe so not an actual regression. Are you okay with closing this issue at this point?

**Comment by kosta709** [comment] 2018-10-03 18:35
but what is the reason of disabling data disks for custom image?
after my manual edit of azuredeploy.json cluster was deployed sucessful with datadisks

**Comment by CecileRobertMichon** [comment] 2018-10-03 18:45
I'm not sure why this was originally designed this way, to be honest. If you want to start a PR to remove that artificial constraint we'll be happy to run testing on it and make sure it doesn't regress any behavior.

**Comment by kosta709** [comment] 2018-10-03 18:53
ok, great!
Thank you
i'm ok to closing this issue

**Closed** 2018-10-03 19:37 UTC
