### ISSUE TITLE
K8s template is not idempotent and can break running cluster

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#344] opened 2017-03-02 02:20 UTC
The generated k8s template is not idempotent, it could be **destructive** if you run the same template again on a running cluster.

## Scenario:
1. Deploy a k8s cluster
2. Expose a service using load balancer
3. Deploy the same template again in the running cluster RG. (for whatever reason, e.g. trying to fix broken agent node, extend the agent pool size etc.)
4. Note that the load balancer of the service will stop working.

## Root cause:
The template has a networkSecurityGroup resource, with a property of an array of networkSecurityRules. The template only contains the default rule for 22 and 443. Running the template will overwrite/replace the existing rules (which contains the rule to allow LB probe).

## The recommend fix:
We should split the networkSecurityRules into separate resource in the template, this way the NSG resource will not contain the rules (thus existing rules will not be replaced), and the 2 nested resource will only add to existing rule set.

**Comment by JackQuincy** [comment] 2017-03-08 21:51
Nitpicky detail: the issue isn't the template being idempotent the template deployed repeatedly will produce the same result every time. The issue is 2 services(acs-engine, k8s) trying to manage the same resource and putting different values in. 

Sadly @weinong investigated this in the past and the recommended fix won't work. The networkSecurityRules aren't tracked resources. So even if we break them out NRP will remove the rules that aren't found in the template that k8s added.  The only solution I've seen that works is to have a separate update template that is missing at least the NSG on making the VNet not depend on it.

**Comment by colemickens** [comment] 2017-03-08 21:55
How does one know? The API makes it look like a tracked resource: `/providers/Microsoft.Network/networkSecurityGroups/myNsg/securityRules/rule1` (https://docs.microsoft.com/en-us/rest/api/network/list-networks-security-rules-within-a-network-security-group) and there exists API calls for just the NSG rules (https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2016-12-01/swagger/networkSecurityGroup.json#L242)

How does one know whether or not they're tracked sub-resources?

**Comment by weinong** [comment] 2017-03-08 22:46
I looked at the NRP manifest which does not have securityRules resource type.

**Comment by colemickens** [comment] 2017-03-08 22:52
This puts us into an unfortunate situation then. I don't see how we can sanely proceed with only doing ARM template deployments given this information.

**Comment by weinong** [comment] 2017-03-08 23:03
You can do a GET template to get the latest snapshot.
https://docs.microsoft.com/en-us/rest/api/resources/resourcegroups#ResourceGroups_ExportTemplate
![image](https://cloud.githubusercontent.com/assets/4204090/23728171/51e86068-0410-11e7-973c-c91b107c8ba3.png)

**Comment by colemickens** [comment] 2017-03-08 23:04
Implementing an intelligent diff for two ARM templates may well be harder than just reconciling the security group. Especially for k8s, there will be a lot of drift. On the other hand, if we know the NSG must at least have these 5 rules, it's probably easier to just do a GET on the NSG, reconcile it, and do a PUT, the same way the k8s cloudprovider does. But either way, we need to think about what ACS-Engine/ACS look like in a world where we keep diverging more from naive template PUTs.

**Comment by anhowe** [comment] 2017-05-01 21:46
@JackQuincy is writing code to do this, and will be able to share this.

**Comment by JackQuincy** [comment] 2017-06-02 18:39
This has been fixed closing

**Closed by JackQuincy** 2017-06-02 18:39 UTC
Labels: orchestrator/k8s, priority/P1
