### ISSUE TITLE
generating azure templates

### ISSUE THREAD

**Issue by Netdoc41** [Azure/acs-engine#3042] opened 2018-05-22 22:03 UTC
**Is this a request for help?**:
yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
It may be an issue 
---

**What version of acs-engine?**:
17
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.7.2

**What happened**:
I have run into a few problems that surface themselves different times depending on what i try. I will try to be descriptive but not so much so that it takes someone 60 minutes to read. :)

1. When i generate the Azure template via the kubernetes-hybrid.json and upload it to the portal. Then do the same with the parameters file. Missing items are a. agent windows source url. b. etcd encryption key there may be a couple more as i see other blanks but not sure if those are just null and will be fine because i never got past the other . 
2. When generating an ssh key via putty and placing that in the key data line. I had thought this would be the full key but when i place that in i get error parsing the api model: invalid character 'r' after object key:value pair. So i tried just placing the thumbprint in there and it did not error. Obviously i am not sure if it works because i have not gotten that far.
3. one of the sets of instructions i tried to follow had us change some keys in the hybrid file first. they are from:

"servicePrincipalProfile": {
  "clientId": "",
  "secret": ""
}
to:

"servicePrincipalProfile": {
  "servicePrincipalClientID": "",
  "servicePrincipalClientSecret": ""
}
however when i do that it errors so once again i am not sure if changing them to a different value will cause other problems.

4. In looking through some issues it seems as though the raw build i downloaded may be older than what i could get if i rebuilt the sourcecode that was posted. So i tried that using the devenv.ps1 which is supposed to run and leave you at a command prompt. But never finishes running it posts these messages 
Successfully built ee88dc73a1e3
Successfully tagged acs-engine:latest

then just sits there like its still processing but does not give me a prompt. I can see that the acs-image container is running but again not sure if that is acceptable. 

Of course i should say that all of the above could just be me not reading the directions carefully enough so please forgive me if that is the case.

**What you expected to happen**:
magic working :)

**How to reproduce it** (as minimally and precisely as possible):
see above

**Anything else we need to know**:
nope

**Comment by CecileRobertMichon** [comment] 2018-05-24 17:11
Hi @Netdoc41, it looks like you are running into several different issues so let's try to fix them one at a time :) Have you tried following https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#acs-engine-the-long-way?

**Comment by Netdoc41** [comment] 2018-05-24 19:40
I think i got the ssh part down. that was a " problem. but the other two i just mentioned not so much here is screenshot https://imgur.com/a/gUFRBB3

**Comment by Netdoc41** [comment] 2018-05-24 21:15
update... Even though the generated templates did not like the upload feature of Azure. Scripting it actually did create everything. Have not testing 100% yet to see if it all is happy

**Comment by CecileRobertMichon** [comment] 2018-06-12 19:10
Closing the issue since it seems resolved, let me know if the issue is unresolved and you want me to reopen

**Closed by CecileRobertMichon** 2018-06-12 19:10 UTC
Labels: question
