### ISSUE TITLE
Docker Daemon commands will be deprecated soon.

### ISSUE THREAD

**Issue by rjtsdl** [Azure/acs-engine#983] opened 2017-07-13 17:46 UTC
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE
---

**What version of acs-engine?**:
All
---

Seems `docker daemon` will be deprecated soon. Here is what from docker. 
https://docs.docker.com/engine/deprecated/#repositoryshortid-image-references

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
ALL

**What happened**:
We will have a break soon if we don't replace docker daemon commands

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by rjtsdl** [comment] 2017-07-13 17:47
There is one PR #982 . But i think we need to fix more than that.

**Comment by seanknox** [comment] 2017-07-13 18:13
Thanks @rjtsdl, good catch I'll create issues or each orchestrator and schedule them.

**Comment by jackfrancis** [comment] 2017-11-06 21:39
duplicate of #984

**Closed by jackfrancis** 2017-11-06 21:39 UTC
Labels: duplicate, orchestrator/dcos, orchestrator/k8s, orchestrator/swarm, orchestrator/swarmmode, priority/P1, ready
