### ISSUE TITLE
Internal-only clusters

### ISSUE THREAD

**Issue by jritsema** [Azure/acs-engine#458] opened 2017-03-31 20:27 UTC
Is there a way (or are there plans) to use acs-engine to create internal-only kubernetes clusters with no public IPs along with custom vnets (i.e., internal corporate apps on an express route vnet)?

**Comment by JackQuincy** [comment] 2017-04-03 20:42
Not currently. Desires yes. Plans not that I'm aware of. Shouldn't be too involved of a change if you make it on the out template from ACS-Engine. PRs are welcome if anyone wants to add the ability to mark a master agent pool internal only and not give it a public ip address in that case.

**Comment by JackQuincy** [comment] 2017-04-03 20:46
There is not currently a way to do this. There have definitely been talks about allowing non public agent pool setups. I'm not up to date on that status of that. Which would be more of a kubernetes thing. As for having a cluster with an internal only loadbalancer on the masters. I don't know of any plans. It should be straight forward to change ACS engine output and possibly ACS Engine to have a no public ip master for the master load balancer. PRs are welcome.

@colemickens Cole do we allow to expose services just inside the vnet but not on the public internet? Is this just cluster IP? for some reason I'm thinking this is slightly different than just exposing a cluster IP.

**Comment by colemickens** [comment] 2017-04-04 19:28
Dupe of #221.

ClusterIP is "virtual" via iptables and thus only works on the nodes of the cluster. An internal load balancer for the Services is needed. There's a PR in progress upstream for that. Other than that #221 details some of the other things that will be required (ACS-Engine will need apimodel to have a flag to say "don't create the External Load Balancer".

There's also some additional work that would need to be done to handle the PKI assets and the connections to the master, maybe. I don't remember exactly, but in a number of places we rely on the external LB  and the real DNS FQDN given to it for connectivity.

**Comment by jritsema** [comment] 2017-04-04 19:36
Thanks so much for the quick reply and I apologize for missing the other issue.  Would you like me to close this one out?

**Comment by colemickens** [comment] 2017-04-04 19:41
Sure. Thanks!

**Closed by colemickens** 2017-04-04 19:41 UTC
Labels: kind/feature, orchestrator/k8s, priority/P2
