### ISSUE TITLE
Introduce an option to display current version

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#356] opened 2017-03-03 17:28 UTC
I'd like acs-engine to have an option to display the current version and/or the git commit from which it was built. Currently, i use a dirty script that name and symlinks acs-engine to the build:

```
#!/bin/bash
cd $GOPATH/src/github.com/Azure/acs-engine
git pull
go build
mv acs-engine acs-engine-`git rev-parse HEAD` ; ln -sf acs-engine-`git rev-parse HEAD` acs-engine
```

**Comment by colemickens** [comment] 2017-03-03 17:44
Dupe of #311

**Closed by colemickens** 2017-03-03 17:44 UTC
