### ISSUE TITLE
Hybrid deployment - kubernetes cannot find windows nodes

### ISSUE THREAD

**Issue by ajorkowski** [Azure/acs-engine#490] opened 2017-04-12 12:53 UTC
Just a heads up. After a fresh pull/build of acs-engine and building a hybrid cluster from scratch everything seems to deploy correctly (no errors in ARM deployment) and it doesn't seem like there is any pending operations. However once I run `kubectl get nodes` I am not able to see the windows nodes. The linux nodes do work and I am able to create services/deployments etc without any issues. The windows nodes are running in azure.

Here is the base template that I am using - I just run acs-engine on it and deploy the output files without any modification. I think this matches up pretty well with the hybrid example config, but maybe something has recently changed? I was able to connect to all the nodes using the acs-engine of about a week ago.
 
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "kalixswarm",
      "vmSize": "Standard_F2s"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool",
        "count": 1,
        "vmSize": "Standard_F2s",
        "availabilityProfile": "AvailabilitySet"
      },
	  {
        "name": "windowspool",
        "count": 2,
        "vmSize": "Standard_F2s",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": "xxxxxxxxxx",
      "adminPassword": "xxxxxxxxxx"
    },
    "linuxProfile": {
      "adminUsername": "kalixhealth",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "xxxxxxxxxxxx"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "servicePrincipalClientID": "xxxxxxxxxxx",
      "servicePrincipalClientSecret": "xxxxxxxxxxx"
    }
  }
}
```

**Comment by colemickens** [comment] 2017-04-13 19:22
cc: @JiangtianLi

**Comment by JiangtianLi** [comment] 2017-04-13 19:37
@ajorkowski Could you collect *.log in c:\k and c:\AzureData on your Windows node? I deployed a mixed cluster recently with 22284cbc1cf020b1e6eb7bd7d200f209c632b100 HEAD and`kubectl get no` shows Windows nodes.

**Comment by ajorkowski** [comment] 2017-04-13 20:18
@JiangtianLi I did spend some time on trying to get into the nodes but I was a bit lost :( Since the node wasn't connected on kubectl I couldn't do proxy commands... I guess I have to add a loadbalancer manually and then RDP using that? If you have any suggestions it would be appreciated and I will run/debug a new cluster later today.

**Comment by JiangtianLi** [comment] 2017-04-13 20:23
@ajorkowski Have you tried RDP SSH tunnel via the master node? This [link](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.windows.md#walkthrough) has the instructions.

**Comment by ajorkowski** [comment] 2017-04-13 20:56
I'll give it a go, but I'm not sure which IP I would use internally? I will try to use the ip addresses that are assigned to the NIC on azure then. 

From memory the route table on azure did not have either of the window nodes' vms/nics added to it, and when I tried to add it manually it was instantly removed by kubernetes (which I thought was kind of cool). If this causes a problem I'll try to access the vm directly some other way.

I'll create a new cluster later today and let you know what I find.

**Comment by JiangtianLi** [comment] 2017-04-13 21:08
@ajorkowski If you go to https://resources.azure.com/ and find your resource group, it has node IP (privateIPAddress) under networkInterfaces.

**Comment by ajorkowski** [comment] 2017-04-13 23:37
Ok, I'm getting the problem with this freshly spun up cluster, and I was able to get into the windows box.

It's quite strange... there is no c:\k folder and this is all that is in the `C:\AzureData\CustomDataSetupScript.log`:

```
Id     Name            PSJobTypeName   State         HasMoreData     Location  
--     ----            -------------   -----         -----------     --------  
1      Job1            BackgroundJob   Running       True            localhost 
```

I'll see if I can run the script manually and see if I can get more of a response....

**Comment by ajorkowski** [comment] 2017-04-13 23:53
Something that might be related - I actually flipped the agent pools so that the linux one is first. I did this as when I was trying to setup an nginx ingress controller the service for the controller would always create a load balancer with a public ip that internally would point to the windows nodes, NOT the linux nodes. When I changed the order of the agent pools, the service would correctly point to the linux node where the controller resides. 

I can see that the $global:PrimaryAvailabilitySetName parameter is set to my linux availability set, so that probably explains that behavior. I'm wondering if this explains why your cluster was created without any problems?

**Comment by JiangtianLi** [comment] 2017-04-14 00:11
@ajorkowski I have linux agent pools first in my json so it doesn't seem to be the problem. Were you able to run CustomDataSetupScript.ps1 manually?

**Comment by ajorkowski** [comment] 2017-04-14 00:34
I'm slowly reverse engineering all the arguments from my azuredeploy.json/azuredeploy.parameters.json (and getting distracted a little bit). I'll have more info soon.

Just as an initial pass though - the fact that there is no k folder, or even a k.zip implies to me that the first step of Get-KubeBinaries didn't even finish? Saying that, when I ran wget on $global:KubeBinariesSASURL manually it did download successfully.

I'm thinking I might try to mess with the azuredeploy.json and redeploy from scratch to get more useful info.

**Comment by JiangtianLi** [comment] 2017-04-14 00:45
@ajorkowski From your CustomDataSetupScript.log, it seems the ps script wasn't executed from the beginning.

**Comment by ajorkowski** [comment] 2017-04-14 00:56
Is that right? In the azuredeploy.json I can see this line:

`"windowsCustomScriptSuffix": " $inputFile = '%SYSTEMDRIVE%\\AzureData\\CustomData.bin' ; $outputFile = '%SYSTEMDRIVE%\\AzureData\\CustomDataSetupScript.ps1' ; Copy-Item $inputFile $outputFile ; Start-Job -command { Invoke-Expression('{0} {1}' -f $outputFile, $arguments) } ; ",`

Which looks like is starting a job to run the script, and this seems to be what is getting piped into the log output (not the actual real output). I'm trying to modify this manually and recreate the cluster so that it will log properly.

**Comment by ajorkowski** [comment] 2017-04-14 01:27
Ok so... I changed the line above and removed the Start-Job command and it worked?! The nodes are available in the cluster and the log file came up with all the output etc. I basically just removed the `Start-Job` wrapper around the `Invoke-Expression` call. 

Here was the final result: 

`"windowsCustomScriptSuffix": " $inputFile = '%SYSTEMDRIVE%\\AzureData\\CustomData.bin' ; $outputFile = '%SYSTEMDRIVE%\\AzureData\\CustomDataSetupScript.ps1' ; Copy-Item $inputFile $outputFile ; Invoke-Expression('{0} {1}' -f $outputFile, $arguments) ; ",`

I don't know... it doesn't really make sense to me....

**Comment by JiangtianLi** [comment] 2017-04-14 01:32
@colemickens @ajorkowski Oh, that's why I see log differently. Seems Cole had some change recently to make it background.

**Comment by colemickens** [comment] 2017-04-14 01:48
Sorry, I hadn't been seeing much in the log that was useful during my experiments. I assume we can make Start-Job pipe output to a file, if that's desired?

But are you saying that removing the `Start-Job` wrapper actually changed the behavior of the installation, or just that you were able to get logs then?

I also changed it so that the bootstrap kubelet output actually goes somewhere too... maybe that'd be sufficient.

None of my changes should have affected core functionality though. Can you let me know if that's what you're observing?

**Comment by colemickens** [comment] 2017-04-14 01:51
It looks like if you want the output from the PS1, we should try to activate Tracing from the PS1 script since it doesn't appear to be possible to tell Start-Job directly to redirect stdout/stderr. But from Googling, it *also* looks like there are caveats around transcribing from inside a background job. I just don't know about PowerShell sometimes...

**Comment by ajorkowski** [comment] 2017-04-14 01:55
@colemickens I modified the azuredeploy.json inline with the change mentioned above, no other changes.

I created the cluster from scratch I would say about 3/4 times while testing and each time the windows nodes were not active. After the change a fresh cluster worked correctly.

Saying that... Apart from the logging problems, I don't see why wrapping the script in a Start-Job would cause these problems... Do you think that maybe the whole context stops once the 'script' is finished and this causes the background job to be cancelled maybe? I'm not really sure how the `CustomScriptExtension` stuff works in Azure...

**Comment by JiangtianLi** [comment] 2017-04-14 01:57
@colemickens In that case, maybe we can tweak Write-Log to redirect to file directly?

**Comment by ajorkowski** [comment] 2017-04-14 02:02
@colemickens Maybe something similar to this: http://stackoverflow.com/questions/26489507/azure-custom-script-extension-tasks-not-running-in-background

I can see in the azuredeploy.json that it is running the command `start /b powershell.exe -ExecutionPolicy Unrestricted -command`. Maybe that works the same as `Invoke-Command` as per that article in that it closes all processes associated with the command?

**Comment by colemickens** [comment] 2017-04-14 02:13
@JiangtianLi yeah, seems like a good idea.

@ajorkowski Hm... I intentionally used `Start-Job` because `Invoke-Command` was not working (as per the S.O. link).

I did a fair amount of testing and did not see nodes not working with that particular PR. Let me take a look at this again when I get home in a few minutes.

Here's the thing though... my change for Start-Job was merged... after this issue was opened. At least eye-balling the dates on GitHub, I think that's true.

**Comment by ajorkowski** [comment] 2017-04-14 02:26
@colemickens This is very true. Yes I can confirm that I first put up this issue before the Start-Job was added (looking at the commit history).

Well, next time I see it happen at least I know where to look/debug. It probably would be useful to have the log so I can give useful information in the case where -nothing- is downloaded, like the first time I ran the cluster while debugging this issue.

**Comment by colemickens** [comment] 2017-04-14 02:50
@JiangtianLi What did the log look like before? Was it a full transcript, or just places where we were manually `Write-Log`ing? I can try to add this back for debug-ability. Apologies if this has made it harder to triage whatever this current issue is...

@ajorkowski One more question... are you seeing these flakes in a particular region or anything? And what commit of ACS-Engine are you currently using? Is it safe to assume it's a commit from master and you're not applying other patches/PRs/changes (other than the Start-Job removal)?

I'm wondering if the region you're deploying to is having a hard time pulling from Storage or something.

**Comment by JiangtianLi** [comment] 2017-04-14 04:14
@colemickens Previous logs are just stdout/stderr of Write-Log. Thank you for looking into it. You are the expert. From the log, it seems the execution of the scripts were put to background even before your change. I'll need to search the history.

**Comment by colemickens** [comment] 2017-04-14 04:31
> From the log, it seems the execution of the scripts were put to background even before your change.

What makes you say this? I don't think that's the case. Before my change... if the kubelet ever got stuck waiting for a CIDR (because master is not working) then it would never complete, blocking the CSE completion and the deployment. So I don't think it was in the background.

After my change, I tested and Windows agents would finish provisioning, even if the master was broken and they didn't make the deployment time out at 90 minutes. (Which was the desired effect of the bug/fix.)

**Comment by JiangtianLi** [comment] 2017-04-14 04:36
@colemickens from @ajorkowski 
> this is all that is in the `C:\AzureData\CustomDataSetupScript.log`:

```
Id     Name            PSJobTypeName   State         HasMoreData     Location  
--     ----            -------------   -----         -----------     --------  
1      Job1            BackgroundJob   Running       True            localhost 
```
That makes me think the script is already executed in background, right?

**Comment by colemickens** [comment] 2017-04-14 04:38
That's due to my change: https://github.com/Azure/acs-engine/pull/478/files#diff-f18f17bd6f84d54a111be39c8fe59d54.
I think @ajorkowski pulled between filing and today. My point earlier was that whatever is making the Windows nodes not show up was probably not a result of my backgrounding change.

**Comment by JiangtianLi** [comment] 2017-04-14 04:46
@colemickens I see. This one was deployed today. I misread. Then we need the CustomDataSetupScript.log from previous cluster. 
@ajorkowski Were you able to collect logs from previous cluster? For the cluster you deployed today, does `kubectl get no` not work for Windows node?

**Comment by ajorkowski** [comment] 2017-04-14 04:57
@colemickens I'm running in westus azure region, and that is correct I pulled the current master without any patches except for the start-job change I made. The cluster I spun up the second time when it worked is working without any issues right now.

@JiangtianLi I rebuilt my cluster 2 times today, the first time had the issue where it just output the $job, and the second I applied the patch and it worked, so I don't have full logs when it failed :( When I first published this issue, I had seen this happen 2/3 times consecutively.

And yes... when I ran `kubectl get no` I could see the master and the linux node, but not the windows nodes (I had two of them).

I just want to point out, the first time today when I spun up the bad cluster. I did not have `C:\k.zip`, `C:\k\` available. Could this be a race condition on the startup of the windows nodes wrt reaching the outside internet? I only ask this as I have seen situations in the clusters where the windows nodes have not been able to access the outside internet (ie calls from my code). Unfortunately I haven't been able to reliably make this happen, and again I didn't have access to the nodes at the time.

**Comment by ajorkowski** [comment] 2017-04-14 04:59
I'll do some cluster delete/rebuild cycles with my patched deploy file - I'll see if I can get it to happen again and get a proper log.

**Comment by JiangtianLi** [comment] 2017-04-14 05:12
@ajorkowski Thanks. I re-read your comment and since with/without Start-Job both had issue and without Start-Job once succeeded, it may well be as Cole suggested - flakiness in accessing storage and downloading zip. Of course more logs would be helpful.

**Comment by colemickens** [comment] 2017-04-14 18:55
The problem is, even the logging that was in place wasn't enough to catch the network errors. As far as I can tell it's only going to be the things that are explicitly written with `Write-Log`.

I'm trying to figure out if there's something like `set -x` for PowerShell. The transcript is... a bit too verbose it seems. Plus, I'm seeing that it's not even doing anything. The Start-Job starts, but then nothing happens... I added a `md $global:KubeDir` at the top, and it *still* doesn't even do that.

**Comment by colemickens** [comment] 2017-04-14 19:08
@ajorkowski were you able to repro without the Start-Job change again (hopefully with logs) ?

**Comment by ajorkowski** [comment] 2017-04-14 19:27
@colemickens Ah, sorry, forgot to put my findings here. I rebuilt the cluster about 5 times last night (with the patched version of my json, so I could get logs) but each time it ran successfully. So unfortunately I don't have any more insight... It does seem whatever was causing the issue is gone for me at least....

If I see it again I will definitely add it here, I will probably be recreating the cluster a few more times.

**Comment by ajorkowski** [comment] 2017-04-14 19:32
Did you want me to try creating the cluster with the un-patched version from master? Maybe the Start-Jobs is actually causing a problem? I could change the powershell script to output directly to the file or something if I need to do logging. I would have to do it later today though.

**Comment by colemickens** [comment] 2017-04-14 20:50
Yeah, if you can. I have a branch here where I tried to get Write-Log to redir to a file, and to run a transcript. But in my attempt(s?) I wasn't getting anything. It wasn't even making `C:\k` even though I added a line to explicitly create it at the beginning of the script. Maybe there is something weird going on with Start-Job.

If you can test w/ and w/o Start-Job back to back a few times, we can maybe figure out if Start-Job is the culprit. It's very weird though, when I tested with it previously it was fine...

**Comment by ajorkowski** [comment] 2017-04-15 01:20
@colemickens Ok, ran a cluster using a fresh master version and the nodes DID NOT come up, so it seems the Start-Job is definitely the cause... Also, I had a look at my reflog and the commit that I had pulled when I first found this issue was https://github.com/Azure/acs-engine/commit/77deacee15307effa255f5bd5007df7026c2fab0, which looks like came out on the 11th and its the exact commit that Start-Job was added.

I'm going to have a play around with the script and see if we can keep Start-Job but still have it work...

**Comment by ajorkowski** [comment] 2017-04-15 02:54
Ok so I was trying out some scripts locally. Take this for example (from windows bash):

```
powershell -command "Invoke-Expression('Start-Sleep -s 1; Add-Content C:\done.txt done ');"
```

That creates a file after 1 second, but you have to wait... If I add `Start-Job` then it doesn't print out a file:

```
powershell -command " Start-Job { Invoke-Expression('Start-Sleep -s 1; Add-Content C:\done.txt done '); } "
```

If I add start /B it actually starts a second context but still no file is created:

```
start /B powershell -command " Start-Job { Invoke-Expression('Start-Sleep -s 1; Add-Content C:\done.txt done '); } "
```

As per this article https://serverfault.com/questions/121979/tools-to-run-a-background-process-command-line-in-windows maybe run something like this? It runs in the background and the file is created.

```
start /min cmd /c powershell -command " Invoke-Expression('Start-Sleep -s 1; Add-Content C:\done.txt done '); "
```

**Cluster Deployment/Possible Fix**
I've made the following changes to the azuredeploy.json file (ie removed `Start-Job` and used `start /min cmd /c powershell`) and the cluster started correctly:

```
"windowsCustomScriptSuffix": " $inputFile = '%SYSTEMDRIVE%\\AzureData\\CustomData.bin' ; $outputFile = '%SYSTEMDRIVE%\\AzureData\\CustomDataSetupScript.ps1' ; Copy-Item $inputFile $outputFile ; Invoke-Expression('{0} {1}' -f $outputFile, $arguments) ; ",

"commandToExecute": "[concat('start /min cmd /c powershell.exe ...
```

**Closed** 2017-04-18 15:52 UTC
Labels: kind/bug, needs more information, orchestrator/k8s, priority/P1, windows
