### ISSUE TITLE
Windows Containers have no outbound connectivity

### ISSUE THREAD

**Issue by Mozanrath** [Azure/acs-engine#3690] opened 2018-08-16 19:08 UTC
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

ISSUE

**What version of acs-engine?**:

Version: v0.20.7
GitCommit: da4127d0
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

I created a cluster with windows nodes using the below template

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "cap-staging-cluster",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId": "$subnet",
      "firstConsecutiveStaticIP": "10.241.255.5",
      "vnetCidr": "10.241.0.0/16"
    },
    "agentPoolProfiles": [
      {
        "name": "windowspool",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "osDiskSizeGB": 200,
        "vnetSubnetId": "$subnet",
        "availabilityProfile": "AvailabilitySet",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": "azureuser",
      "adminPassword": "$adminPw",
      "windowsPublisher": "MicrosoftWindowsServer",
      "windowsOffer": "WindowsServerSemiAnnual",
      "windowsSku": "Datacenter-Core-1803-with-Containers-smalldisk"
    },
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "$keyData"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "$clientKey",
      "secret": "$spKey"
    }
  }
}
```

**What happened**:

Template successfully created, but any deployed windows containers were unable to access the internet. Was able to resolve ips from host names (dns worked), but unable to connect to sites outside the cluster (cannot connect to google even). Whats odd was that the windows nodes running the containers was able to connect to the internet. The outbound connectivity issue seemed limited to the containers themselves.

**What you expected to happen**:

Containers should have access to the internet, especially since the nodes do have access.

**How to reproduce it** (as minimally and precisely as possible):

Deploy a cluster with windows nodes on a custom vnet.

**Anything else we need to know**:

The only extra step was that I did manually update the azuredeploy.json file to add a "subnet" parameter because of this known issue: https://github.com/Azure/acs-engine/issues/1767

**Comment by CecileRobertMichon** [comment] 2018-08-16 19:11
This is a duplicate of #3280

**Comment by CecileRobertMichon** [comment] 2018-08-17 17:56
Closing to avoid duplicates

**Closed by CecileRobertMichon** 2018-08-17 17:56 UTC
Labels: windows
