### ISSUE TITLE
Unable to acs-engine deploy with v0.17.0: 'The number of template variables limit exceeded. Limit: '256' and actual: '257'

### ISSUE THREAD

**Issue by neurot1cal** [Azure/acs-engine#3015] opened 2018-05-18 20:13 UTC
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.17.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.10.2

**What happened**:
```
INFO[0004] Starting ARM Deployment (ad3-k8s-dev-west-a-989867831). This will take some time...
INFO[0006] Finished ARM Deployment (ad3-k8s-dev-west-a-989867831). Error: resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The number of template variables limit exceeded. Limit: '256' and actual: '257'. Please see https://aka.ms/arm-template/#variables for usage details.'."
ERRO[0006] {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The number of template variables limit exceeded. Limit: '256' and actual: '257'. Please see https://aka.ms/arm-template/#variables for usage details.'."}}
FATA[0006] resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The number of template variables limit exceeded. Limit: '256' and actual: '257'. Please see https://aka.ms/arm-template/#variables for usage details.'."
```

**What you expected to happen**:
Deploy successfully

**How to reproduce it** (as minimally and precisely as possible):
```
☁  v0.17.0  ./acs-engine deploy --api-model ./_output/<REDACTED>/apimodel.json \
    --subscription-id <REDACTED> \
    --resource-group <REDACTED> \
    --ca-certificate-path <REDACTED>/ca.crt \
    --ca-private-key-path <REDACTED>/ca.key \
    --auth-method client_secret \
    --client-id <REDACTED> \
    --client-secret <REDACTED> \
    --location "westus" \
    --force-overwrite
```

**Anything else we need to know**:
cluster_definition.json
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": <REDACTED>,
      "vmSize": "Standard_D11_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "linuxpool2",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]
      },
      {
        "name": "windowspool1",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      },
      {
        "name": "windowspool2",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": <REDACTED>,
      "adminPassword": <REDACTED>
    },
    "linuxProfile": {
      "adminUsername": <REDACTED>,
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<REDACTED>"
          }
        ]
      }
    },
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": <REDACTED>,
      "secret": <REDACTED>
    }
  }
}
```

**Comment by jackfrancis** [comment] 2018-05-18 20:25
Is this a regression from v0.16.0?

**Comment by neurot1cal** [comment] 2018-05-18 20:36
@jackfrancis I used this same definition in v0.16.2 successfully. Generated from scratch using this cluster definition.

**Comment by neurot1cal** [comment] 2018-05-18 20:39
Same failure running from master;
```
INFO[0004] Starting ARM Deployment (ad3-k8s-dev-west-a-1826111904). This will take some time...
INFO[0006] Finished ARM Deployment (ad3-k8s-dev-west-a-1826111904). Error: resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool2-17595707-0/extensions/cse0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."
ERRO[0006] {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool2-17595707-0/extensions/cse0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."}}
FATA[0006] resources.DeploymentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidTemplate" Message="Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool2-17595707-0/extensions/cse0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."
☁  bin [master] ⚡ ./acs-engine version
Version: canary
GitCommit: 6457e15b
GitTreeState: dirty
```

**Comment by jackfrancis** [comment] 2018-05-18 20:40
Yep, thanks. We'll look into how to deal with this for the next release. :(

**Comment by neurot1cal** [comment] 2018-05-18 21:31
@jackfrancis Something else may be broken with extensions entirely, I removed all references to extesnsions in my clusterdef, and am getting this;

```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": <REDACTED>,
      "vmSize": "Standard_D11_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "linuxpool2",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
      },
      {
        "name": "windowspool1",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      },
      {
        "name": "windowspool2",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "VirtualMachineScaleSets",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": <REDACTED>,
      "adminPassword": <REDACTED>
    },
    "linuxProfile": {
      "adminUsername": <REDACTED>,
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<REDACTED>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": <REDACTED>,
      "secret": <REDACTED>
    }
  }
}
```

```
INFO[0004] Starting ARM Deployment (ad3-k8s-dev-west-a-1296466505). This will take some time...
INFO[0860] Finished ARM Deployment (ad3-k8s-dev-west-a-1296466505). Error: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
ERRO[0860] {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n  \"status\": \"Failed\",\r\n  \"error\": {\r\n    \"code\": \"ResourceDeploymentFailure\",\r\n    \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n    \"details\": [\r\n      {\r\n        \"code\": \"VMExtensionProvisioningError\",\r\n        \"message\": \"VM has reported a failure when processing extension 'vmssCSE'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=9\\n[stdout]\\n\\n[stderr]\\n\\\".\"\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
FATA[0860] resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."
```

**Comment by neurot1cal** [comment] 2018-05-21 18:26
@CecileRobertMichon Interesting... I'm working from master after the PR just went through;
```
☁  acs-engine [master] ⚡ ./bin/acs-engine version
Version: canary
GitCommit: b0236c0e
GitTreeState: dirty
```

for the extensions fix, but I'm still seeing an `ERRO[0007] {"error":{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Compute/virtualMachines/k8s-linuxpool1-35976173-0/extensions/cse-master-0' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'."}}`

Here's the cluster definition I'm using;
```
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.10"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": <REDACTED>,
      "vmSize": "Standard_D11_v2"
    },
    "agentPoolProfiles": [
      {
        "name": "linuxpool1",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      },
      {
        "name": "linuxpool2",
        "count": 5,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "extensions": [
          {
            "name": "prometheus-grafana-k8s"
          }
        ]
      },
      {
        "name": "windowspool1",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      },
      {
        "name": "windowspool2",
        "count": 3,
        "vmSize": "Standard_D11_v2",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks",
        "osType": "Windows"
      }
    ],
    "windowsProfile": {
      "adminUsername": <REDACTED>,
      "adminPassword": <REDACTED>
    },
    "linuxProfile": {
      "adminUsername": <REDACTED>,
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<REDACTED>"
          }
        ]
      }
    },
    "extensionProfiles": [
      {
        "name": "prometheus-grafana-k8s",
        "version": "v1",
        "rootURL": "https://raw.githubusercontent.com/Azure/acs-engine/master/"
      }
    ],
    "servicePrincipalProfile": {
      "clientId": <REDACTED>,
      "secret": <REDACTED>
    }
  }
}
```

**Comment by CecileRobertMichon** [comment] 2018-05-21 18:29
@neurot1cal the PR to fix VMSS and Windows isn't merged yet (#3031). The one that went in fixed Promotheus with k8s and Linux.

**Comment by neurot1cal** [comment] 2018-05-21 18:30
@CecileRobertMichon Not using VMSS here if you look at the Cluster Definition - This is using `AvailabilitySet`.

**Comment by CecileRobertMichon** [comment] 2018-05-21 18:31
Hmm let me try to repro, thanks for catching that!

**Comment by neurot1cal** [comment] 2018-05-22 04:18
@CecileRobertMichon I was able to get the ARM deployment to actually go by modifying `azuredeploy.json` by changing;

```
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', '-master-', copyIndex(variables('masterOffset')))]",
```

to

```
      "name": "[concat(variables('masterVMNamePrefix'), copyIndex(variables('masterOffset')),'/cse', copyIndex(variables('masterOffset')))]",
```

This caused template validate to stop failing, but once the cluster spun up all of the prometheus CSE's failed; 
![image](https://user-images.githubusercontent.com/11523744/40341885-78c4f030-5d3c-11e8-825c-cd1b81166413.png)

```
☁  acs-engine [master] ⚡ az group deployment create --name "ad3-k8s-dev-west-b" --resource-group "ad3-k8s-dev-west-b" --template-file ./_output/ad3-k8s-dev-west-b/azuredeploy.json --parameters ./_output/ad3-k8s-dev-west-b/azuredeploy.parameters.json
Deployment failed. Correlation ID: 778879ca-3f74-4688-90bf-fc93995a6477. {
  "status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "BadRequest",
            "message": "{\r\n  \"error\": {\r\n    \"code\": \"BadRequest\",\r\n    \"message\": \"Multiple VMExtensions per handler not supported for OS type 'Linux'. VMExtension 'cse-master-1' with handler 'Microsoft.Azure.Extensions.CustomScript' already added or specified in input.\"\r\n  }\r\n}"
          }
        ]
      }
    ]
  }
}
```

**Comment by neurot1cal** [comment] 2018-05-22 17:15
@CecileRobertMichon Awesome! Thank you

**Comment by huajunzhao** [comment] 2018-05-23 03:11
Hi @CecileRobertMichon,

Thanks for the fix.

It looks like the deployment is still failed.

OPERATION ID7D0BCEDB12F43E24
TRACKING ID5b69691b-120d-4f72-8189-a9220448301e
STATUSConflict
PROVISIONING STATEFailed
TIMESTAMP5/23/2018, 10:53:39 AM
DURATION36 minutes 27 seconds
TYPEMicrosoft.Compute/virtualMachines/extensions
RESOURCE ID/subscriptions/58043194-91b4-4390-be55-dd64251a67bd/resourceGroups/kzha_k8s_rg/providers/Microsoft.Compute/virtualMachines/k8s-agentpool1-35463463-0/extensions/cse-agent-0
STATUSMESSAGE{
"status": "Failed",
"error": {
"code": "ResourceDeploymentFailure",
"message": "The resource operation completed with terminal provisioning state 'Failed'.",
"details": [
{
"code": "VMExtensionProvisioningError",
"message": "VM has reported a failure when processing extension 'cse-agent-0'. Error message: "Enable failed: failed to execute command: command terminated with exit status=4"."
}
]
}
}
RESOURCEk8s-agentpool1-35463463-0/cse-agent-0

I'm using 0.17.1 acs-engine: https://github.com/Azure/acs-engine/releases/tag/v0.17.1 and also regenerate the arm template, but the deployment still has the same issue.

Notes: I was performing this on China Azure.

**Comment by CecileRobertMichon** [comment] 2018-05-23 04:31
@huajunzhao this looks like a separate issue. Please open a new issue and include the apimodel (make sure you remove secrets) you are using to create the cluster.

**Comment by CecileRobertMichon** [comment] 2018-05-29 23:33
@neurot1cal can I close this issue?

**Comment by neurot1cal** [comment] 2018-05-30 00:50
Sounds good!

**Closed** 2018-05-30 01:54 UTC
Labels: kind/bug

**Comment by sshepel** [comment] 2018-07-15 15:02
Same for acs-engine 0.19.2

**Comment by dysolution** [comment] 2018-07-23 18:45
Same for acs-engine 0.20.0.

**Comment by navicore** [comment] 2018-08-10 18:44
getting this on 0.20.7 for a config that works in 0.18.8 

I've paired the config down as far as I can go to get it under the 256 in 0.18.  but 0.20.7 generates 261 variables with the same script.  had to roll back to 0.18 for now.

**Comment by jackfrancis** [comment] 2018-08-10 18:45
@navicore https://github.com/Azure/acs-engine/pull/3649 will fix things
